### ISSUE TITLE
.Xsession_error upon wake-from-suspend

### ISSUE THREAD

**Issue by halocaridina** [enkore/i3pystatus#102]
On Arch Linux (up to date) : when waking laptop from suspend via systemd/lid being closed, following consistently appears in ~/.xsession_error:

no connectionException in Thread-5 at Sun Aug 24 12:15:55 2014
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/i3pystatus/core/threading.py", line 68, in **call**
    self.workload()
  File "/usr/lib/python3.4/site-packages/i3pystatus/core/modules.py", line 67, in **call**
    self.run()
  File "/usr/lib/python3.4/site-packages/i3pystatus/mail/**init**.py", line 44, in run
    unread = sum(map(lambda backend: backend.unread, self.backends))
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

In some cases, i3pystatus becomes unresponsive and does not update, requiring Shift+$mod+R (i.e., a reload of i3). 

Modules/plugins being used:

grep status i3pystatus.conf ("battery" occurs twice since Lenovo T440S possesses two (2) separate batteries):

status.register("clock",
status.register("weather",
status.register("text",
status.register("battery",
status.register("battery",
status.register("pulseaudio",
status.register("backlight",
status.register("temp",
status.register("text",
status.register("disk",
status.register("mem",
status.register("load",
status.register("cpu_usage",
status.register("shell",
status.register("text",
status.register("shell",
status.register("mail",
status.register("network",
status.register("wireless",

Please let me know if you need additional information and thank you again for this great project.

**Comment by sileht** [comment]
Perhaps https://github.com/enkore/i3pystatus/pull/380 solves this issue.

Cheers,

**Comment by lasers** [comment]
Solved via #380? Can we close this issue?
