### ISSUE TITLE
Battery does not give time estimation

### ISSUE THREAD

**Issue by Phyks** [enkore/i3pystatus#112]
Hi,

With my laptop model, my battery does not report current_now information in uevent.

When it is charging, I do have the info in `/sys/class/power_supply/BAT/current_now` (but not in uevent file).
When it is discharging, I don't have any such information.

What do you think about implementing fallbacks to test directly the file ? Or to rely on `acpi` information ?

**Comment by terminalmage** [comment]
What are the contents of ``/sys/class/power_supply/BAT/current_now``?

**Comment by Phyks** [comment]
Hmm, I was having this issue quite some time ago, with another laptop which I do not have anymore.

This is no longer relevant, as my new laptop works fine with the current implementation in `i3pystatus` and I cannot check on my old laptop for extra infos or specific contents.

I think the best thing to do is close this issue, and let anyone having similar issue reopen it and comment.

Thanks
