### ISSUE TITLE
Multiple "instances" per module

### ISSUE THREAD

**Issue by teto** [enkore/i3pystatus#150]
Let me detail what I mean by "instance": for example in the clock module, by default with the mousewheel we can change the format.
I wish it were possible to do the same with :
- the mail module (ie switch between accounts with a click or mousewheel, easy with https://github.com/enkore/i3pystatus/pull/149) 
- or the network module (switch between interfaces to see their respective IPs).
- or media players. For instance I use mpd for music and vlc for audio. I wish i could switch between mediaplayers (i3pystatus could even detect which one is playing and display controls according to focus) while having both of them at the same place on the bar.

I wish it is clear and wonder if it interests others or if it looks too crazy.

**Comment by cprn** [comment]
Isn't it possible by adding the `on_click` callback that would unregister one module and register the other? I didn't check but it seems doable.
