### ISSUE TITLE
Refresh the bar

### ISSUE THREAD

**Issue by Phyks** [enkore/i3pystatus#155]
Hi,

I set a high interval between refresh for most of my plugins, as I do not need realtime updates often.

But sometimes, it could be nice to have a direct realtime feedback, when changing brightness through keyboard keys for instance. Then, a nice solution would be to handle a `kill -USR1` and refresh the whole bar on such signal.

What do you think ?

**Comment by teto** [comment]
...or when a cronjob updates your mailbox, it would be nice if it could refresh the display.

**Comment by facetoe** [comment]
I think this would be a great feature. It would also be cool if click events could be handled immediately without waiting for the module to be called again.

**Comment by enkore** [comment]
Implemented in #223
