### ISSUE TITLE
interval setting not respected ?

### ISSUE THREAD

**Issue by teto** [enkore/i3pystatus#160]
I am trying to test an implementation for https://github.com/enkore/i3pystatus/issues/155. My test consists in setting a high interval to update the clock (5sec), and force the update via sending SIGUSR1 to i3pystatus. 
Apparently when I run python3 myStatus.py, it updates the clock every second instead of every 5 sec as I would like (so I can't do my test). Any idea why ? (I am using master version)

Here is the myStatus.py:
```
# -*- coding: utf-8 -*-↲
from i3pystatus import Status↲

status = Status(standalone=True)↲

status.register("clock",
                interval=5,                                  
                format=[
                    ("%a %-d %b %X", 'Europe/Paris'),
                ],
                )
status.run()
```

**Comment by enkore** [comment]
Works for me?

**Comment by facetoe** [comment]
This also works as expected for me as well. It looks like the status JSON is emitted every second but the module is only updated every 5 seconds.

**Comment by enkore** [comment]
That's on purpose however: https://github.com/enkore/i3pystatus/blob/master/i3pystatus/core/io.py#L67

**Comment by teto** [comment]
I would like to say I was drunk but I was just stupid, it indeed works as intended, got abused by the JSON status emitted every second. Sorry.
