### ISSUE TITLE
Calendar widget

### ISSUE THREAD

**Issue by teto** [enkore/i3pystatus#164]
It would be nice if once could consult the next caldav events in his calendar from i3bar.
I've been using thunderbird lightning but events appear only if thunderbird runs in background. 
I've recently tried khal (http://lostpackets.de/khal/index.html) and apparently it relies on python bindings such as icalendar (http://icalendar.readthedocs.org/en/latest/) to load *.ics from a directory.

I may try to code sthg in 2/3 months but if anyone has other way to implement it.

**Comment by drwahl** [comment]
This feature exists for Google Calendar as of 67142bc6fee702c9d66685787a19d26c8d70a8dd.  If you are looking for more/different backends, those are still amiss.

**Comment by teto** [comment]
Just wanted to let people know I have started working on a khal module at https://github.com/teto/i3pystatus/tree/calendars . No idea when I can finish this for a PR though so feel free to take over.

**Comment by teto** [comment]
Posted on https://github.com/enkore/i3pystatus/pull/460
