### ISSUE TITLE
[RFC] Provide option to use keyring to store sensitive credentials.

### ISSUE THREAD

**Issue by facetoe** [enkore/i3pystatus#165]
Several modules require username/password pairs, such as the reddit, github and mail modules. Storing these credentials in the clear is bad security. It would be nice if we could offer the option to use [keyring](https://pypi.python.org/pypi/keyring) instead to make things a little more secure. 

It is already possible to do this in the config, however some users may not know of the keyring module and integrating its functionality into i3pystatus would make it easier for them to take advantage of it. 

Implementing this would be easy. A setting could be added to each of the modules that require credentials to indicate that the keyring should be used instead of user/pass pairs. The only issue then is setting the credentials for the first time. If we agreed on a format such as `modulename.credential` we could provide instructions for setting them via the Python shell, or provide a small utility to help users set the values.

Let me know what you guys think.

**Comment by teto** [comment]
I sync my dotfiles via git and as such is concerned by your point. I didn't know keyring but it looks like a nice solution. I personally appreciate programs that look into "$HOME/.netrc" to retrieve their password (like offlineimap and others). There does not seem to be a corresponding backup for keyring :'(

**Comment by facetoe** [comment]
It looks like it is possible to write custom keyring backends and to specify at runtime which one to use. It should be pretty straightforward to write one that looks in "$HOME/.somedir" to retrieve credentials if you wanted to have copies of your credentials somewhere.

**Comment by enkore** [comment]
One could handle this by making the `password` options optional and using keyring to retrieve the password if no `password` is specified. Or we could use a special sentinel object (i.e. at some prominent module `KEYRING=object()`) that can be specified as a password.

**Comment by facetoe** [comment]
I like the idea of integrating this into the settings system. I'll play around a bit when I get the chance and try to get a prototype running for you guys to check out.

**Comment by teto** [comment]
If it can inspire you https://github.com/untitaker/vdirsyncer/issues/14

**Comment by facetoe** [comment]
Nice, that looks good. Can't hurt to support both keyring and netrc. Good find!
