### ISSUE TITLE
Example for file

### ISSUE THREAD

**Issue by s-hell** [enkore/i3pystatus#168]
I'm trying to get the file module running. Can anyone show me an example. I always get exceptions...

**Comment by Arvedui** [comment]
the files module needs at least two arguments components and format.

components is a dict which looks like this:

```python
{'entropy': (int, '/proc/sys/kernel/random/entropy_avail'),}
```

you can than use the keys in format.
```python
status.register('file', components={'entropy': (int, '/proc/sys/kernel/random/entropy_avail')},
                format='{entropy}')
```

If you still have problem please post your configuration.

**Comment by s-hell** [comment]
Works like a charm.
