### ISSUE TITLE
Improve truncating in MPD module

### ISSUE THREAD

**Issue by modprobe** [enkore/i3pystatus#169]
Just something to consider: I have found the current method of handling the truncation of MPD output somewhat suboptimal. I think it would be more intuitive if one could specify a total length that the output string should not exceed and (a list of) field(s) that would be truncated in order to achieve that certain length.

It should not be that hard to implement; unfortunately I don't have time for it at the moment.

**Comment by Arvedui** [comment]
How about this:

- Add a parameter "max_len" 
- Use whatever catches first (max_len or text_len)
- "max_len" takes equal from all specified fields 
- Value of Zero disables them
- Maybe rename "text_len" to "max_field_len"

specifying fields to be truncated is already possible.

I will try to implement that tomorrow, if that's what you want.

**Comment by modprobe** [comment]
That would be great!

Just to specify what I meant by "list of fields": In my opinion it doesn't make much sense to truncate, say, the progressed time, but at the same time if you have a title and and an artist that are both very long, you wouldn't want only the title to be cut short, but rather both artist and title (or the other specified fields) to be shortened by (roughly) the same amount so it fits into the proposed "max_len".

**Comment by Arvedui** [comment]
didn't had much time for this today sorry :/

Maybe tomorrow, but first day at new job so not very likely.
I will finish this next weekend at the latest.
