### ISSUE TITLE
i3 4.9 shows red background for disk space

### ISSUE THREAD

**Issue by hobarrera** [enkore/i3pystatus#176]
As of i3 4.9, I've noticed that the disk space plugin's output has a red background:

![i3-disk-space](https://cloud.githubusercontent.com/assets/730811/6505078/3042fa58-c31d-11e4-9c4d-228646753e61.png)
(I think this image is worth more than I can explain).

My [config](https://github.com/hobarrera/dotfiles/blob/master/home/.config/i3/status.py#L36-L37) includes no fancy settings for this.

I've only 62% of my disk space in use, so I don't think there should be any reason for this to be red (just clarifying this in case this was the formerly expected behaviour and it's only now been fixed).

I'm running i3pystatus 3.32.

**Comment by facetoe** [comment]
I've also noticed a change in i3 4.9, but in my case a red border is drawn around the load and diskspace. It is only there sometimes though.

**Comment by hobarrera** [comment]
> I've also noticed a change in i3 4.9, but in my case a red border is drawn around the load and diskspace. It is only there sometimes though.

I don't have the `load` plugin active, so I can't speak about it, however, the diskspace plugin shows the red background all of the time, not sometimes (though I admit I only upgraded a few hours ago).

**Comment by facetoe** [comment]
I managed to get a screenshot. I have no idea what triggers the border to be drawn.

![x](https://cloud.githubusercontent.com/assets/1366896/6505678/7ec13002-c37f-11e4-8164-513d76fd4b15.png)

**Comment by enkore** [comment]
Maybe `urgent`?

**Comment by richese** [comment]
Yes, I think it is the urgent flag. #171 should solve this.

**Comment by hobarrera** [comment]
Yup, looks like it's #171. I wonder why i3 4.9 triggered this. Was urgent not being handled there properly?

Can we hope to see this on v3.33 soon?

**Comment by enkore** [comment]
urgent just didn't do anything until 4.9

>   • i3bar: respect the urgency flag on status blocks

**Comment by hobarrera** [comment]
I guess that all makes this issue unnecessary. Thanks!
