### ISSUE TITLE
I get the "status_command exited unexpectedly" error when I run i3pystatus 3.32-1 directly from the git repo using the Archlinux AUR, but when I download it from the package i3pystatus from the AUR of the same version it runs fine

### ISSUE THREAD

**Issue by t3zla** [enkore/i3pystatus#177]
Also on another note, I get a red box around my "disk" module output and sometimes around my load output. Is this a bug or a feature I need to turn off?

Here is my i3stat.py config:

http://pastebin.com/raw.php?i=G1VfKvtq

**Comment by facetoe** [comment]
The red box us due to i3bar honoring urgent now - https://github.com/enkore/i3pystatus/issues/176.

Do you get any useful information if you run your config from the shell?

**Comment by t3zla** [comment]
With the package "i3pystatus" from the AUR:
http://pastebin.com/XzY1an5v

With the package "i3pystatus-git" frim the AUR:
http://pastebin.com/20saYdVN

**Comment by t3zla** [comment]
Also I am unclear on whether or not the "urgent" thing is a bug or a feature. How do I turn it off?

**Comment by facetoe** [comment]
I installed `i3pystatus-git` from the AUR and it worked fine. Looking at the error that is thrown It could be that your `LANG` environment variable is not set. I am able to reproduce your error by unsetting this variable. What happens if you run:

    lang, enc = os.environ.get('LANG', None).split('.', 1)

In the python3 shell?

With the urgent color, it's a feature. It's module specific so to turn it off you need to change your module settings to never hit the critical limit. So for example in the `load` module you would set `critical_limit` to a value like 100 or something.

**Comment by t3zla** [comment]
Yep it is not set. How would I go about setting it?

**Comment by richese** [comment]
There are many ways to set it. 
Creating ~/.config/locale.conf with your prefered locale is probably the best option.
For example:
```
locale -a
echo "LANG=en_US.UTF-8" > ~/.config/locale.conf
```
Also see related page on [ArchWiki](https://wiki.archlinux.org/index.php/Locale#Setting_the_locale).

**Comment by t3zla** [comment]
With the load module I want it to go critical, I just want it to change the color of the text like it used to, not have a red box

**Comment by t3zla** [comment]
Just set critcal_limit on the disk module and it did not remove the red box

**Comment by t3zla** [comment]
Using the AUR package "i3pystatus-git" removes the red boxes. I belive they are different from the critical_limit as critical_limit changes the color of my text and setting the critical limit really low removes the red boxes but highlights my text red
