### ISSUE TITLE
network module "color_up" function is not working, while color_down is

### ISSUE THREAD

**Issue by t3zla** [enkore/i3pystatus#179]
I am running the latest version of i3pystatus via the AUR package "i3pystatus-git" and while color_up is correctly set to a valid color, the module shows up as white text and when I run i3pystatus through the command line it says "color=null" in the network module output. color_down works however and shows the correct color and output. I tried changing the color to the same one as color_down but that did nothing.

Here is my output for an up network and a down network when I run "python .i3/i3stat.py":

http://pastebin.com/jitSkgq2

And here is my i3stat.py config:

http://pastebin.com/A1haTuQq

Every other color for every other module I am using works

**Comment by facetoe** [comment]
Yup, this is a bug. I've submitted a pull request with the fix.
