### ISSUE TITLE
The critical identifier for the load module is a red box instead of the color specified in the configuration

### ISSUE THREAD

**Issue by t3zla** [enkore/i3pystatus#182]

**Comment by facetoe** [comment]
I think this box is drawn by i3bar so it could be overwriting the critical color defined in i3pystatus.

**Comment by t3zla** [comment]
So is it a problem on my end? How would I go about resolving it? I only launch i3pystatus in my i3 config

**Comment by facetoe** [comment]
i3pystatus doesn't draw the box, that's a feature of i3bar. I don't think you can change it. Maybe you could ask them to make the color configurable?

**Comment by t3zla** [comment]
I have not had the box until updating about 5 days ago. It used to be a colored font for the "load" module. I do not run i3bar just i3pystatus. Shouldn't they be independent?

**Comment by facetoe** [comment]
See #176 - `urgent` now causes the box to be drawn. 

i3bar is what i3pystatus is displayed in, it doesn't do any actual rendering itself.

**Comment by t3zla** [comment]
So is there a way to set the critical identifyer back to a color instead of a red box?

**Comment by facetoe** [comment]
I think you'd need to talk to i3bar about that.

**Comment by enkore** [comment]
Uh I guess this is upstream and/or Pango markup (cf. #220) related, so I'm closing this, if no one objects...
