### ISSUE TITLE
ImportError: cannot import name 'Status'

### ISSUE THREAD

**Issue by felinfo** [enkore/i3pystatus#184]
Hello.

I am trying to use i3pystatus, but it shows me the error "ImportError: cannot import name 'Status'". Can anyone help me?.

Thank you very much.

**Comment by facetoe** [comment]
Could you provide some more information:

* distro
* version
* how you installed i3pystatus
* full stack trace

**Comment by felinfo** [comment]
Hello.

I'm using Arch Linux. I installed i3pystatus from Yaourt (yaourt -S i3pystatus-git) . I use this configuration file: http://i3pystatus.readthedocs.org/en/latest/configuration.html . If I run "python i3pystatus.py", this show the error "ImportError: cannot import name 'Status' ". When I add the bar in i3wm configuration file, this show a message error. I don't know how obtain the full stack trace.

Thank you.

**Comment by facetoe** [comment]
Can you run:

    python -c "help('modules')" | grep i3pystatus

And:

    python -c "import i3pystatus; print(dir(i3pystatus))"

And paste the output?

**Comment by enkore** [comment]
The script can't be named "i3pystatus.py", because that's the name of
the i3pystatus package.

See 3.28 changelog: http://docs.enkore.de/i3pystatus/changelog.html#id5

**Comment by felinfo** [comment]
python -c "help('modules')" | grep i3pystatus
CDROM               abc                 i3pystatus          setuptools

python -c "import i3pystatus; print(dir(i3pystatus))"
['IntervalModule', 'Module', 'SettingsBase', 'Status', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'core', 'extend_path', 'formatp', 'h', 'logger', 'logging', 'main', 'os']

I tried with other name for the script, but I got the same error.

**Comment by enkore** [comment]
> python -c "import i3pystatus; print(dir(i3pystatus))"
> ['IntervalModule', 'Module', 'SettingsBase', 'Status', 'all', 'builtins', 'cached', 'doc', 'file', 'loader', 'name', 'package', 'path', 'spec', 'core', 'extend_path', 'formatp', 'h', 'logger', 'logging', 'main', 'os']

> I tried with other name for the script, but I got the same error.

Maybe you're using a different Python for running the script than the Python you used for that command? Or a different virtualenv (if you have any)?

**Comment by felinfo** [comment]
I solved!.
Here what I done:

 2213  cd .i3/
 2215  mv i3pystatus.py i3pystatus_conf.py 
 2217  cd /usr/local/bin/
 2218  sudo ln -s ~/.i3/i3pystatus_conf.py 
 2220  cd
 2221  cd .i3/
 2226  sudo chmod +x i3pystatus_conf.py 
 2227  python i3pystatus_conf.py 

Thanks enkore and facetoe !. You can close the thread.

**Comment by felinfo** [comment]
My error now is "alsa: Missing Python module 'alsaaudio'". How can I import this module?. Thank you.

**Comment by facetoe** [comment]
You'll need to install that one - https://aur.archlinux.org/packages/python-pyalsaaudio/

**Comment by felinfo** [comment]
Thank you facetoe. I solved this error.

But I got new errors with MPD and Wireless:

-> MPD:

Exception in Thread-2 at jue 19 mar 2015 13:25:51 CET
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/i3pystatus/mpd.py", line 64, in _mpd_command
    sock.send((command + "\n").encode("utf-8"))
AttributeError: 'NoneType' object has no attribute 'send'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/i3pystatus/core/threading.py", line 68, in __call__
    self.workload()
  File "/usr/lib/python3.4/site-packages/i3pystatus/core/modules.py", line 129, in __call__
    self.run()
  File "/usr/lib/python3.4/site-packages/i3pystatus/mpd.py", line 81, in run
    status = self._mpd_command(self.s, "status")
  File "/usr/lib/python3.4/site-packages/i3pystatus/mpd.py", line 66, in _mpd_command
    self.s = socket.create_connection((self.host, self.port))
  File "/usr/lib/python3.4/socket.py", line 512, in create_connection
    raise err
  File "/usr/lib/python3.4/socket.py", line 503, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused


-> Wireless. (I have installed netifaces and basiciw):

"wireless: Missing Python module 'i3pystatus.wireless'"

**Comment by facetoe** [comment]
How have you configured MPD? Can you connect as your own user using something like `mpc`?

With the other error, there isn't a wireless module. You might want to dig around in the network module.

**Comment by felinfo** [comment]
I solved it! Thanks facetoe.

**Comment by johnfraney** [comment]
@felinfo I'm getting that same wireless error using the sample config and after having installed all the necessary dependencies:

`wireless: Missing Python module 'i3pystatus.wireless'`

Do you remember how you fixed that?

**Comment by galaux** [comment]
@felinfo: would you please care to elaborate on how you manage to solve this issue? Some are interested in solving this too…

**Comment by enkore** [comment]
>  ConnectionRefusedError: [Errno 111] Connection refused

with mpd is very likely just a configuration issue (or a permission issue, when using UNIX sockets)

> "wireless: Missing Python module 'i3pystatus.wireless'"

See changelog, wireless was "merged" into network a while ago. http://docs.enkore.de/i3pystatus/changelog.html#r3-33

**Comment by galaux** [comment]
Oh ok, you mean there is no "wireless" module anymore (The error message is rather confusing). Changing `"wireless"` to `"network"` in my configuration fixed it:

```
status.register("network",
    format_up="📶 {essid} {quality:03.0f}%",
    format_down="📶",
    color_up="#38912b",
    color_down="#BF3939",
    )
```

Works like a charm, thank you :)
