### ISSUE TITLE
SyntaxError: invalid syntax on Debian

### ISSUE THREAD

**Issue by s-hell** [enkore/i3pystatus#185]
I'm trying to install i3pystatus on Debian. I get the following error:

Extracting i3pystatus-3.32-py3.2.egg to /usr/local/lib/python3.2/dist-packages
  File "/usr/local/lib/python3.2/dist-packages/i3pystatus-3.32-py3.2.egg/i3pystatus/github.py", line 19
    unread_marker = u"●"
                       ^
SyntaxError: invalid syntax

  File "/usr/local/lib/python3.2/dist-packages/i3pystatus-3.32-py3.2.egg/i3pystatus/weather.py", line 34
    "Fair": (u"\u2600", "#FFCC00"),
                     ^
SyntaxError: invalid syntax

  File "/usr/local/lib/python3.2/dist-packages/i3pystatus-3.32-py3.2.egg/i3pystatus/core/util.py", line 386
    bar = u'_▁▂▃▄▅▆▇█'
                     ^
SyntaxError: invalid syntax

Adding i3pystatus 3.32 to easy-install.pth file
Installing i3pystatus script to /usr/local/bin

Installed /usr/local/lib/python3.2/dist-packages/i3pystatus-3.32-py3.2.egg
Processing dependencies for i3pystatus==3.32
Finished processing dependencies for i3pystatus==3.32

**Comment by facetoe** [comment]
Looks like the 'u' prefix for unicode is no longer necessary. I've submitted a fix (#186), but in the meantime you could remove the prefix and it should work fine.

**Comment by s-hell** [comment]
Fixed it!
