### ISSUE TITLE
clock: datetime/pytz vs time

### ISSUE THREAD

**Issue by kyrias** [enkore/i3pystatus#197]
Is there any reason for using datetime and pytz instead of just using the ``time.strftime``function which will do localtime directly, and work correctly with things like `%z`?

**Comment by teto** [comment]
I wanted to have the time for different timezones at the same time (via scrolling on the clock module). Is that possible without pytz ?

**Comment by kyrias** [comment]
It can be done by setting the `TZ` environment variable and then running`time.tzet` and then the `time` modules output will be in that timezone. I’m not sure how to do it in i3pystatus though, and I’m interested in how you’d want it and how you did it.

**Comment by richese** [comment]
It is possible without pytz just like @kyrias said.
Here is what came up with: richese@e31c58f1ade860dc497b424aff7bc971928249a6.

**Comment by teto** [comment]
I am sadly not a python guru, if this code accomplishes the same
functionalities and removes the dependency, I am all for it.
