### ISSUE TITLE
Updatecheck module for pacman and aur

### ISSUE THREAD

**Issue by binaryplease** [enkore/i3pystatus#200]
Hello,
an update checker would be very useful for pacman and aur on linux arch.
I'm not sure if I will be able to implement it since I'm not a python coder but if anyone wants to do it I'll be happy to use it.

The "checkupdates" command would be useful for that.

Just a proposal.

Cheers.

**Comment by richese** [comment]
It's quite easy to do using that script for packages from repos. 
Not sure how to handle AUR though. There are way too many AUR helpers and I don't think they have a common way of handling AUR packages. But I haven't really looked into it so I might be wrong here.

For now I have this [snippet](https://gist.github.com/richese/3dc938c704ea1668148e) for repo packages that you can try using.

**Comment by enkore** [comment]
Thanks, added it to the wiki (so it's easier to find) - https://github.com/enkore/i3pystatus/wiki/Arch-Linux-Update-Reminder
