### ISSUE TITLE
add alert and critical colors to disk and cpu_usage modules

### ISSUE THREAD

**Issue by k0377** [enkore/i3pystatus#225]
`mem` has options for: alert_color, critical_color
`disk` has options for critical_color only
`cpu_usage` has none of it

please add alert and critical colors to other modules as well, where it makes sense.

**Comment by enkore** [comment]
Why would it make sense for cpu_usage? Intermittent high CPU usage is quite normal and actually good (better than longer low CPU usage for the same work, from a power consumption perspective)

**Comment by gutodisse1** [comment]
For cpu_usage: https://github.com/enkore/i3pystatus/pull/247

**Comment by k0377** [comment]
consistency
