### ISSUE TITLE
Display problems with two network connections

### ISSUE THREAD

**Issue by s-hell** [enkore/i3pystatus#227]
I'm having some strange problems displaying my network configs. My status.py looks like this:

status.register("network",
    interface="eth0",
    dynamic_color=False,
    format_down="{interface}",
    color_up="#008800",
    format_up="{interface}: {v4cidr}",)

status.register("network",
    interface="wlan0",
    dynamic_color=False,
    format_down="{interface}",
    color_up="#008800",
    format_up="{interface}: {essid} ({quality:02.0f}%) {v4cidr}",)

But this is being displayed: ![network](https://www.pcspinnt.de/network.png)

**Comment by enkore** [comment]
Maybe you scrolled on the blocks? By default scrolling cycles through the interfaces. This isn't stored however.

Add `on_rightclick=None, on_upscroll=None, on_downscroll=None` to disable this behaviour.

**Comment by richese** [comment]
Another solution may be to add the `ignore_interfaces` setting.
Add `ignore_interfaces = ["lo", "wlan0"]` to first instance and `ignore_interfaces = ["lo", "eth0"]` to second. This should result in the same behaviour @enkore mentioned and keep the config a little bit more human readable.

**Comment by enkore** [comment]
This  is probably now resolved
