### ISSUE TITLE
Create format_full for battery module

### ISSUE THREAD

**Issue by belak** [enkore/i3pystatus#232]
Because there won't be time remaining when the battery is full, in my instance there is an extra space in the format. It would be nice to have something in addition to `no_text_full` which already exists.

**Comment by terminalmage** [comment]
As of the creation of this issue last July, this was actually already possible, at least in the master branch. This [documentation improvement](https://github.com/enkore/i3pystatus/pull/350/files#diff-a15e9e4dff50fd01f0698a3c9c706f40R139) should help make this more clear.
