### ISSUE TITLE
Status Dictionary Module

### ISSUE THREAD

**Issue by Elder-of-Ozone** [enkore/i3pystatus#233]
I'm attempting to build a new module and use dictionary mapping to create alternative names. I have looked closely at the three examples (Battery.py, mpd.py and now_playing.py) and built a minimal version of what I think would work.

Here is the pastebin. There is two parts. The first part is the module itself and the second part is included in the i3pystatus config. The first part is the module itself and the second part is included in the i3pystatus config. 

http://pastebin.com/bCCL2Pc0

When using the module, I get the following error message
"Module 'TestStatusDictionary': invalid option 'status'

Is there anything I'm missing?

**Comment by facetoe** [comment]
Try adding a setting tuple with an entry for `status`. You can look at one of the other modules for an exampe.

**Comment by enkore** [comment]
http://docs.enkore.de/i3pystatus/i3pystatus.core.html#i3pystatus.core.settings.SettingsBase.settings

**Comment by Elder-of-Ozone** [comment]
Ah! Cheers. That was definitely a fundamental thing I forgot. I reworked my module and forgot to rename this in the setting. Hence arose my question and minimal example.
