### ISSUE TITLE
@require(internet) won't work behind a corporate proxy

### ISSUE THREAD

**Issue by paulollivier** [enkore/i3pystatus#234]
Hi,

After wondering why the `i3pystatus.updates` module wasn't reporting any available update when there is, I looked at the code, and saw `i3pystatus/core/util.py:362` where you are making a connection to a google dns server.

The problem is: outside DNS is blocked in many corporate networks.

I was wondering why you choose this way to check for an internet connection, and if you were open to the idea of merging a PR using HTTP, for instance.
Or maybe be able to specify the `host:port` couple to be used when checking for internet access, since the protocol used doesn't seem to be of interest in the current implementation?

Thank you for your time.

**Comment by enkore** [comment]
I did that because it's a very fast and very low traffic method. But yeah I see how it can cause trouble with some tight firewall setups. I'd say changing the target host just to "google.com" and the port to 80 should work well with almost any firewall.

**Comment by paulollivier** [comment]
Yeah, I changed the method to try to connect to one of our internal servers. I was just wondering if it was possible to implement it as a configuration option.

I gather from your response that you are not fond of getting a merge request related to this?

**Comment by facetoe** [comment]
It might be tricky to implement as it's a function without arguments passed to the `require` decorator. Any ideas on how the configuration could be implemented?

**Comment by t3zla** [comment]
Would it not work to just change it to 8.8.8.8?

**Comment by paulollivier** [comment]
Woopsie, sorry, I missed the reply notification.

@facetoe: To be honest, the only way I have found (yet) implies the use of global variables to save the configuration. I fear that a major refactoring would be needed to make it "The Right Way"™.

**Comment by richese** [comment]
How about changing `internet` to a class and making the adress a class variable?
This variable can be set from the config file if you import `i3pystatus.core.util.internet` or by adding an optional argument to Status class.
``` python
class internet:

    address = ("google-public-dns-a.google.com", 53)

    def __new__(self):
        try:
            socket.create_connection(self.address, 1).close()
            return True
        except OSError:
            return False
```

**Comment by enkore** [comment]
#280 merged, implementing this
