### ISSUE TITLE
Launch program with parameters on_click

### ISSUE THREAD

**Issue by floli** [enkore/i3pystatus#240]
I try to launch htop on_click of the CPU usage bar:

```
status.register("cpu_usage_bar",
                on_leftclick = ["konsole","-e", "htop"])
```
```
status.register("cpu_usage_bar",
                on_leftclick = ["konsole -e htop"])
```
```
import subprocess 

def launch_htop():
    subprocess.call(["konsole", "-e", "htop"])

status.register("cpu_usage_bar",
                on_leftclick = [launch_htop])
```
```
status.register("cpu_usage_bar",
                on_leftclick = launch_htop)
```

but non of them work. Just launching the konsole, without parameters works.

**Comment by teto** [comment]
related to https://github.com/enkore/i3pystatus/pull/231 . I've got no time right now to update the PR with tests so anyone welcome to do it.

**Comment by richese** [comment]
#257 should also fix this issue.
`on_leftclick = "konsole -e htop"` should work now.


>def launch_htop():
>    subprocess.call(["konsole", "-e", "htop"])

I also used this approach until now but with `subprocess.Popen`.
