### ISSUE TITLE
The cmus module disapears/flickers randomly after listening for a little while. It doesn't just say cmus is not running, it totally disapears.

### ISSUE THREAD

**Issue by t3zla** [enkore/i3pystatus#252]
I am taking a look at it myself and attempting to fix it but I wanted to formally post a bug report just in case someone else has this problem.

**Comment by schroeji** [comment]
I experienced the same problem and fixed it in pull request #253 .

**Comment by enkore** [comment]
#253 merged, if it didn't fix this please reopen
