### ISSUE TITLE
i3pystatus blocks after application has started

### ISSUE THREAD

**Issue by joepvd** [enkore/i3pystatus#254]
If a mouse action is set to run a long running application, clicks on the status bar are ignored until the application is closed. This can be observed wit hthe default settings when the pulseaudio plugin is enabled. From what I casn tell, after opening the a pavucontrol application from i3pystatus, subsequent clicks on this and other modules are being acted upon. As soon as the blocking application is closed, the clicks are replayed. 

**Expected behavior**
Processes are spawned fork/exec-ed from the i3pystatus process, and i3pystatus does not care if this process runs, if it exited, and if so, erroneously or not.

**Comment by enkore** [comment]
Fixed in merged PR #257
