### ISSUE TITLE
[question] on_middleclick callback

### ISSUE THREAD

**Issue by Anon1234** [enkore/i3pystatus#259]
Can't find anything about middle click callback in docs. Is there a way to bind an action to it?

**Comment by teto** [comment]
From modules.py
```
   6     settings = (                                                                                 
    27         ('on_leftclick', "Callback called on left click (see :ref:`callbacks`)"),                
    28         ('on_rightclick', "Callback called on right click (see :ref:`callbacks`)"),              
    29         ('on_upscroll', "Callback called on scrolling up (see :ref:`callbacks`)"),               
    30         ('on_downscroll', "Callback called on scrolling down (see :ref:`callbacks`)"),           
    31         ('on_doubleleftclick', "Callback called on double left click (see :ref:`callbacks`)"),   
    32         ('on_doublerightclick', "Callback called on double right click (see :ref:`callbacks`)"), 
    33         ('on_doubleupscroll', "Callback called on double scroll up (see :ref:`callbacks`)"),     
    34         ('on_doubledownscroll', "Callback called on double scroll down (see :ref:`callbacks`)"), 
    35         ('multi_click_timeout', "Time (in seconds) before a single click is executed."),         
    36         ('hints', "Additional output blocks for module output (see :ref:`hints`)"),              
    37     )                    

```
so no it's not supported.
Clicks could use an update to support buttons based on the click number (and keep aliases) for backwards compatibility. I've been thinking about this for quite some time without the time to implement it. I would be glad to use previous/next buttons of mouse.

**Comment by enkore** [comment]
Middle mouse button could be added as usual, and we could add something like `on_unhandled` or `on_fallback` that gets all click events that were not handled otherwise.

**Comment by hasB4K** [comment]
I have, along with a better click support, do like you said @enkore:
* Simplify the switch between all action
* Add the middle click support
* In case of failing, we can handle that in a unhandled callback

If you have any suggestion on this, I will be glad to hear it.

**Comment by teto** [comment]
We should support all mouseclicks, i.e. if a mouse has 30 buttons, i3pystatus should support it. I know I would like to be able to use my previous/next mouse buttons. i3 sends the button id, so upon click, i3pystatus could check if there is an on_click<ID> parameter and use that as a callback. For backwards compatibility, one can provide a dict to map on_leftclick to on_click0, on_rightclick to on_click2 (IIRC) etc...

**Comment by hasB4K** [comment]
I have added the possibility with #339 to have the mouse positions and the button_id in a callback.
I check, with the `inspect` module, if the mouse callback have the optional parameters `button_id`, `pos_x` or `pos_y` and I pass them as parameter if one of them is present. I do that with a keyword arguments.

However, I think the name `unhandled` was not a good one. I think the name `other` fit the need.

Example in a config file:
``` python
@get_module
def test(self, **kw):
    self.logger.debug("test: %s" % str(kw))

@get_module
def test1(self, button_id):
    self.logger.debug("test: %d" % button_id)

status.register("text",
                text="test",
                on_rightclick=[test],
                on_otherclick=[test1]
                )
```

Log output:
```
i3pystatus.text.Text: button=3, cb='<function test at 0x7fe67ab46ae8>', args=[], kwargs={'pos_x': 2474, 'button_id': 3, 'pos_y': 9}, type='Python callback'
test: {'pos_x': 2474, 'button_id': 3, 'pos_y': 9}
i3pystatus.text.Text: button=6, cb='<function test1 at 0x7f83de6c7bf8>', args=[], kwargs={'pos_y': 7, 'button_id': 6, 'pos_x': 2476}, type='Python callback'
test: 6
```
