### ISSUE TITLE
Uncatched error in mail module 

### ISSUE THREAD

**Issue by teto** [enkore/i3pystatus#269]
...kills the whole i3pystatus display rather then being isolated:
In my .xsession-errors
`Error opening database at /home/teto/Maildir/.notmuch: No such file or directory`

**Comment by enkore** [comment]
Backtrace?

If it occurs during setup (i.e. some init method) then it's intentional to blow stuff up. If it occurs inside some run method, well, then... it's a bug.

**Comment by enkore** [comment]
Please reopen if still current
