### ISSUE TITLE
Alsa module doesn't unmute other mixers

### ISSUE THREAD

**Issue by k1-hedayati** [enkore/i3pystatus#271]
It seems like `self.alsamixer.setmute(not muted)` mutes all mixers but in unmuteing only `Master` mixer gets unmuted and others like `Headphone` and `Front` remain muted.
Fun fact is `alsaaudio.Mixer().setmute(False)` successfully unmutes all mixers.
I tried to add these lines to my config but it results in funny and unexpected behaviors.
```
status.register("alsa", interval=0.5, mixer='Master')
status.register("alsa", interval=0.5, mixer='Headphone')
status.register("alsa", interval=0.5, mixer='Front')
```

I think if we remove default arguments from `create_mixer` method it solves this issue.

**Comment by teto** [comment]
I believe this is a known problem unrelated to i3pystatus but rather from your system (ubuntu ?). I have the same problem if in alsamixer I mute and then unmute master, I still get no sound because it didn't unmute other channels. I removed pulseaudio and now it works but that's the easy way out I guess.

**Comment by k1-hedayati** [comment]
Oh, thank you, I've removed `pulseaudio` and everything seems to be fine. But I wonder why when I create `Mixer` class without any args it doesn't have issues

**Comment by enkore** [comment]
Probably because you'll mute and unmute all channels in that case.

**Comment by k1-hedayati** [comment]
> Probably because you'll mute and unmute all channels in that case.

Isn't that more sensible? When you press mute you don't want any sound from your computer, if you want to control a specific Mixer you just add it to your config.

**Comment by enkore** [comment]
That's debatable. Say for example you have two mixers in your status bar, one for output, one for input. Often you'd just want to mute your microphone.

**Comment by k1-hedayati** [comment]
`alsaaudio.Mixer().setmute(True)` only mutes Master. Headphone and Front mixers and doesn't change others

**Comment by enkore** [comment]
Yes, but I couldn't mute my microphone then could I?

If this works for normal ALSA drivers - and it seems so, but breaks with PulseAudio's ALSA emulation then I think PA is to blame. As a workaround one can use the pulse module for i3pystatus.
