### ISSUE TITLE
Pango Markup Hint Doesn't Work

### ISSUE THREAD

**Issue by facetoe** [enkore/i3pystatus#284]
I tried out the Pango hint today and can't seem to get it to work. The example in the [docs](http://docs.enkore.de/i3pystatus/configuration.html#hints) just shows the literal text instead of formatting it in i3bar. I played around with various modules and markup with no success, it always shows the literal string instead of formatting it. 

For example, the following simple module (markup example from the [pango docs](https://developer.gnome.org/pango/stable/PangoMarkupFormat.html)):

```python
status.register("text",
                text="<span foreground=\"blue\" size=\"x-large\">Blue text</span> is <i>cool</i>!",
                hints={"markup": "pango"})
```

Outputs the following JSON:

```json
{
  "instance": "140573011452928",
  "name": "i3pystatus.text.Text",
  "markup": "pango",
  "full_text": "<span foreground=\"blue\" size=\"x-large\">Blue text</span> is <i>cool</i>!"
}
```
But does not render the markup in the i3bar. Any ideas why this doesn't work?

**Comment by richese** [comment]
The output looks fine. In fact it works in my bar.

The only reason I can think of is that you do not have pango support compiled in your i3.
Arch packages have pango support out of the box. Did you compile i3 yourself?
Do you have `pango` package installed?
It should also show up if you run `ldd /usr/bin/i3bar | grep pango`

**Comment by facetoe** [comment]
My i3 is installed with `yaourt` from the `i3-git` package. Here is the output of `ldd /usr/bin/i3bar  | grep pango`:

	libpangocairo-1.0.so.0 => /usr/lib/libpangocairo-1.0.so.0 (0x00007f657eb65000)
	libpango-1.0.so.0 => /usr/lib/libpango-1.0.so.0 (0x00007f657e91a000)
	libpangoft2-1.0.so.0 => /usr/lib/libpangoft2-1.0.so.0 (0x00007f657b16a000)
`
Initially I didn't have the `pango` package installed so I installed it and recompiled i3, still no luck. 

Here is my bar config:

```
bar {
    status_command    python3 /home/facetoe/git/i3pystatus/i3pystatus_conf.py
    position          top
}
```

I'm sure I tried using the pango markup several months ago and it worked fine, somehow I've broken it on my system!

**Comment by richese** [comment]
Yay, I was able to reproduce it!
It's in the config. You need to use freetype font in the bar to enable pango. [i3 doc on fonts](http://i3wm.org/docs/userguide.html#fonts)

My bar config looks like this:
```
bar {
    font              pango:Monospace 8
    position          top
    status_command    python ~/.config/i3/pystatus_config.py
    workspace_buttons yes
    strip_workspace_numbers yes
}
```

**Comment by facetoe** [comment]
Thanks @richese, now it's working! I read that section of the docs earlier today and still missed the error in my config!
