### ISSUE TITLE
Ability to use the module format for callbacks

### ISSUE THREAD

**Issue by teto** [enkore/i3pystatus#300]
In order to launch callbacks depending on the module status, for instance clicking on mpd module could open file explorer to current song via using "nautilus {{current_song}}" etc... 

Another example  when clicking on the clock, I would like to be able to set:
```
clock = status.register(
    "clock",
    format=[
        ("%a %-d %b %X", 'Europe/Paris'),
        ("Format 0", 'Europe/London'),
    ],
    on_leftclick=["/usr/bin/urxvtc",'-e', 'ikhal', "at", "{current_time}"],
```

Had a quick look at the code (that changed a bit since last time I checked), and there does not seem to be a standard way to format a string with modules parameters ? Would adding to each module a format member the way to go? or .. ?

**Comment by enkore** [comment]
This is an interesting issue. Most modules are written in the form of gather_info => create_some_dict => self.output = format_a_string(some_dict), so some_dict is basically lost in processing from a data flow perspective.

We could define the paradigm that formatter data ("some_dict") should be saved to an instance variable, e.g. `output_data`. That would allow access from the callbacks.

**Comment by teto** [comment]
It's a bit sad indeed to see this carefully generated dict go to waste. I am not a python architect so I dunno how to best implement it, your solution should work. 
The 'run' member comes down updating this dict.
I have not many cycles but I can update a few modules if you decide on a design.

**Comment by facetoe** [comment]
I don't mind updating some modules as well if a design is decided on. It's a pretty simple change but it would add a lot of flexibility to what can be done with the modules.

**Comment by mxlian** [comment]
:+1: to this

**Comment by enkore** [comment]
Some modules - list in 612b8b0 - don't use this yet, but it should work, mostly.

**Comment by teto** [comment]
I get an "ALSA: name fdict is not defined" error.

**Comment by teto** [comment]
This fixed the problem thx.
