### ISSUE TITLE
Modules not executing external commands

### ISSUE THREAD

**Issue by mxlian** [enkore/i3pystatus#301]
Passing commands like: 
```
status.register("disk",
...
    on_leftclick = "baobab",)
```

aren't being executed...

**Comment by mxlian** [comment]
Remote debugging shows:

![screenshot from 2016-01-12 12-05-45](https://cloud.githubusercontent.com/assets/2795329/12262974/e1e1af02-b92b-11e5-9471-3a72287d4e8c.png)

**Comment by mxlian** [comment]
I'll write a patch for it

**Comment by enkore** [comment]
My bad, I should have caught that when merging the introducing commit. I amended de8b03f to master already.

**Comment by mxlian** [comment]
:+1:

**Comment by mxlian** [comment]
I didn't added it to the changelog because was introduced after 3.33. Btw, when do you plan to release a new version? Is there some kind of roadmap?

**Comment by enkore** [comment]
I'll plan to release a new version in the next few weeks, preferably still in January. As far as I'm aware there is no roadmap. i3pystatus is a bit like a plugin repository in this regard I guess.
