### ISSUE TITLE
Configure maildir module

### ISSUE THREAD

**Issue by rogorido** [enkore/i3pystatus#303]
This is not exactly an issue, just a question. I'm trying to use the maildir module, but I'm not able to configure it. I have the following:

status.register("mail",
                backends=[maildir.MaildirMail()],
                directory="/home/name/Mail/inbox",
                format="P {unread}",
                log_level=20,
                hide_if_null=False,)

and:

from i3pystatus.mail import maildir

but I get an error: invalid option 'directory'...

Any idea? (and thanks for the very good package!)

**Comment by facetoe** [comment]
It looks like the `directory` setting is part of the `MaildirMail` module, so this should work:

```python
status.register("mail",
	backends=[maildir.MaildirMail(
		directory="/home/name/Mail/inbox")],
	format="P {unread}",
	log_level=20,
	hide_if_null=False,)
```

**Comment by rogorido** [comment]
exactly! Thanks a lot!

**Comment by facetoe** [comment]
No worries!

**Comment by rogorido** [comment]
I think that it would be maybe a good idea to put an example in the doc about how to use the mail backends. There is already an example about the updates modules which is very helpful...

**Comment by rogorido** [comment]
Thanks!
