### ISSUE TITLE
Callbacks: Passing self to external callbacks?

### ISSUE THREAD

**Issue by mxlian** [enkore/i3pystatus#304]
The call to the user_open is passing self to it. I saw in other modules they write a wrapper to avoid this, i'll patch it like that.

![screenshot from 2016-01-14 10-23-55](https://cloud.githubusercontent.com/assets/2795329/12320543/74529238-baa9-11e5-8363-d992a5f26509.png)

**Comment by mxlian** [comment]
@enkore I saw  the github and reddit modules having the same problem. They solve it with custom member callbacks for each url they want to open. Could make sense to solve this problem somehow globally?

Like: 
* Add a wrapper to user_open to filter 'self' out, and put it available in **core.utils**
* Changing the user_open to get rid of 'self' (seems wrong to do this)
* Any better solution?

**Comment by enkore** [comment]
Does someone use the availability of *self* to external (non member) callbacks? Even if so, it should be kinda rare and a workaround is possible (Status.register returns the instance which can be passed back to the callback manually if necessary)

**Comment by mxlian** [comment]
For me it seems to be the most clean solution

**Comment by richese** [comment]
I find this feature quite useful actually. For example if you want to wrap a callback to be executed only if certain conditions are met or most likely when you just want value of some module variable.

To me it looks like `user_open` is missing the `self` parameter because it was forgotten when the switch to configurable callbacks happened, since its definition is older than that (14c0528be56485696a8563495daa8352254abb91 and 33aba4b0845d3c278fb0887d750f1feae5e04d78 ). Even its docstring states that it is meant to be called from callbacks, not that it is a callback.
I would add the missing parameter to `user_open` and then check all modules that use it.

Also it could be helpful to rename `self` to `module` in non-member callback [documentation](http://docs.enkore.de/i3pystatus/configuration.html#callbacks) to make it less confusing?

**Comment by mxlian** [comment]
@richese should than the user_open remain in *core.util* ?

**Comment by enkore** [comment]
Another solution came to mind. We could normally remove the self argument, but provide a decorator that adds it back again (e.g. stack inspection), in case one needs self for something more involved.

Pro:
- Easy to use for both cases (any Python function can be used, but involved use cases are not made harder than necessary)
- Only small change needed for existing user callbacks

Con:
- Magic decorator

**Comment by enkore** [comment]
Sample implementation for discussion: https://gist.github.com/enkore/90acffa13df5e7ee8ec7

**Comment by mxlian** [comment]
@richese do you know of a module using this?

@enkore i tried your gist, didn't work :/

```
In [29]: print("object", cc)
object <__main__.CallingClass object at 0x7f6a1ab4d2e8>

In [30]: cc.call_that(called_noself)
called_noself

In [31]: cc.call_that(called_self)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-31-874c18d8a872> in <module>()
----> 1 cc.call_that(called_self)

<ipython-input-23-635808e6e8be> in call_that(self, function)
      2         def call_that(self, function):
      3                 # This would be the callback dispatcher
----> 4                 function()
      5 

<ipython-input-15-2fd305d6c40c> in call_wrapper(*args, **kwargs)
      9         stack = inspect.stack()
     10         caller_frame_info = stack[1]
---> 11         self = caller_frame_info.frame.f_locals["self"]
     12         # not completly sure whether this is necessary
     13         # see note in Python docs about stack frames

AttributeError: 'tuple' object has no attribute 'frame'

```

Traced:

```
> <ipython-input-1-5257bb0a45aa>(15)call_wrapper()
-> self = caller_frame_info.frame.f_locals["self"]
(Pdb) l
 10  	        caller_frame_info = stack[1]
 11  	        print (caller_frame_info)
 12  	        dir (caller_frame_info)
 13  	        import pdb
 14  	        pdb.set_trace()
 15  ->	        self = caller_frame_info.frame.f_locals["self"]
 16  	        # not completly sure whether this is necessary
 17  	        # see note in Python docs about stack frames
 18  	        del stack
 19  	        function(self, *args, **kwargs)
 20  	    return call_wrapper
(Pdb) print (caller_frame_info)
(<frame object at 0x7ffb288671f8>, '<ipython-input-1-5257bb0a45aa>', 26, 'call_that', ['        function()\n'], 0)
(Pdb) dir (caller_frame_info)
['__add__', '__class__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__gt__', '__hash__', '__init__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'count', 'index']
(Pdb) 
``` 

I think the original idea of @enkore the cleanest: removing the *self* and passing it manually as *args if required.

**Comment by enkore** [comment]
Ah yes, it is a recent change in Python. I use 3.5 and wrote it using the 3.5 docs, prior to 3.5 a list was returned, which was changed to a named tuple in 3.5. I'll fix the gist.

**Comment by mxlian** [comment]
knock knock
