### ISSUE TITLE
run Update module in background

### ISSUE THREAD

**Issue by teto** [enkore/i3pystatus#311]
I use the apt-get backend. I would like a click on the module to run a check (easily done) but also to display a message like "pending..." in order to know if it really is running the check.
I suppose it would require to launch the apt-get update (for instance) in a thread. Dunno how hard it is though.

**Comment by richese** [comment]
This can be implemented quite easily.
I am not sure if this pending message should appear every time or only if refresh is initiated from a specific `refresh` click event? The latter would make more sense I guess.

**Comment by teto** [comment]
As a personal preference, I would like to know when it's refreshing data, not only when I click. It gives an idea of when the last check ran and can also explain why a connection would slow a bit.

**Comment by enkore** [comment]
The updates module will almost always run in a separate thread due to the interval.

39e2c64 does the right thing for you?

**Comment by teto** [comment]
works great. Thanks !

2016-02-01 12:21 GMT+01:00 enkore <notifications@github.com>:
