### ISSUE TITLE
alsa cannot unmuted headphone 

### ISSUE THREAD

**Issue by ismaelpuerto** [enkore/i3pystatus#312]
Hi

When I mute the sound all work fine. But when i unmuted sound, only unmuted Master, headphone keep mute.
my config (simple):
status.register("alsa",
    format="♪{volume}",)

I have F22
$ rpm -qa |grep alsa
alsa-lib-1.0.29-1.fc22.x86_64
alsa-utils-1.0.29-1.fc22.x86_64
alsa-lib-devel-1.0.29-1.fc22.x86_64

**Comment by enkore** [comment]
Do you perhaps use PulseAudio and this is related to #271?

**Comment by ismaelpuerto** [comment]
yes, Yesterday when update my system, I install pulseaudio when update firefox 44
