### ISSUE TITLE
Chained (standalone=False) mode - does anybody use this feature?

### ISSUE THREAD

**Issue by enkore** [enkore/i3pystatus#313]
I noticed that chained mode was broken for quite a while, no one complained about it. We could remove a good bit of code and simplify some things if we choose to remove this feature.

Does anybody use this feature?

**Comment by teto** [comment]
what does it do xD ?

**Comment by enkore** [comment]
It's from the early days of i3pystatus, when there weren't many modules. It basically allows you to append the output of i3pystatus to another status line generator, i3status for example.

In theory it can also be used to add additional output e.g. by shell scripts, but that's easier to do from within i3pystatus.

**Comment by enkore** [comment]
So, I just looked at removing it, and noticed that we wouldn't really save anything, all the functionality is also used with click events. So standalone=False will stay, but I will change the default to standalone=True.
