### ISSUE TITLE
`online` plugin does not update if network is offline at startup

### ISSUE THREAD

**Issue by WhyNotHugo** [enkore/i3pystatus#336]
If my network is offline at starup, the `online` plugin says `offline`. If I then start the network, it will say offline indefinitely.

If I reload or restart i3, the status is then updated. Further disconnections/reconnections update the status as expected.

**Comment by hobarrera** [comment]
I tried to debug this further, and found that this is partially solaar's fault (specifically, when the device is charging). See pwr/Solaar#260.
