### ISSUE TITLE
updates backend for dnf

### ISSUE THREAD

**Issue by ncoop** [enkore/i3pystatus#357]
Any interest in updates for rpm-based distros?

Here's a working dumb implementation that parses output from `dnf check-update`. (There's a python api but this commit doesn't use it.)

https://github.com/ncoop/i3pystatus/commit/458ae8f3f6e35bfc6af7d80e1fe0622067127989

Also, how about making updates provide the actual list, say as a notification on click? We already have it if we got the count.

**Comment by ncoop** [comment]
Setting aside that last question, should I pr this?

**Comment by enkore** [comment]
Sure, I'd be interested in how you create the notification-on-click? :) (xmessage?)

**Comment by ncoop** [comment]
Nice. Moved the display issue to #364
