### ISSUE TITLE
Bad status line in xkblayout

### ISSUE THREAD

**Issue by k1-hedayati** [enkore/i3pystatus#359]
When I run `subprocess.check_output("setxkbmap -query | awk '/layout/,/variant/{print $2}'", shell=True).decode('utf-8').replace("\n", " ").strip()` this is what I get `us,ir grp:menu_toggle,caps:hyper,grp_led:scroll` which I don't think is a good output, layout check command needs refactoring.

**Comment by enkore** [comment]
#365
