### ISSUE TITLE
Display actual updates

### ISSUE THREAD

**Issue by ncoop** [enkore/i3pystatus#364]
The updates module uses whatever backend is available to get the number of updates. The output of the check operation should be preserved so the user can see it.

There's already DesktopNotification in desktop.py, and icon sets include `software-update-available`. It's straightforward to set up a call to it in Updates, perhaps `on_rightclick`. It's not the only way to display though.

However, there needs to be a field set up in updates to store the text output, and all of the backends need to be updated to use it. How to deal with multiple backends being allowed?

**Comment by enkore** [comment]
> How to deal with multiple backends being allowed?

Unique package names, if multiple backends supply a package name, the later backend wins?

**Comment by enkore** [comment]
Implemented by #366
