### ISSUE TITLE
[solaar] is only for logitech devices

### ISSUE THREAD

**Issue by sbmueller** [enkore/i3pystatus#403]
The solaar module is unable to find my bluetooth device. After a little investigating, I saw that the script uses `solaar-cli` command, which gives the following output when run by myself:

```
$ solaar-cli show
WARNING: solaar-cli is deprecated; use solaar with the usual arguments
usage: solaar {show,config,pair,unpair} ...
solaar: error: too few arguments
```

The script tries to find my device now via regex, which cannot work here. Is there a workaround or is this an actual issue?
BTW I run Fedora 23 with solaar 0.9.2-4.

**Comment by sbmueller** [comment]
Finding my device also does not work when using `solaar` instead:
```
$ solaar show
solaar: error: Logitech receiver not found
```

**Comment by enkore** [comment]
I guess you'd want to take this upstream to [solaar](https://github.com/pwr/Solaar)...

**Comment by sbmueller** [comment]
> Using solaar-cli instead of solaar should / may be fixed independently of your issue with solaar not finding your device, I think?

Yes. As I found out now, solaar only seems to work with Logitech devices. I'm not using a Logitech device, may this be the reason for my second issue? Maybe it should be made clear in the module reference, that this is Logitech only (now it says "Shows status and load percentage of bluetooth-device").
