### ISSUE TITLE
Clicking actions not working in uname module.

### ISSUE THREAD

**Issue by mr-ubik** [enkore/i3pystatus#406]
The code displays correctly, however when I try to click it nothing happens. 

```
@get_module
def sys_info(module):
    if module.format == "{nodename}":
        module.format = "{sysname} {release} on {machine}"
    else:
        module.format = "{nodename}"

status.register("uname", format="{nodename}", on_rightclick=sys_info)
```

Am I doing something wrong or is there a bug?

**Comment by richese** [comment]
Uname is not an interval module so the output value is only set once at start up in its `init` method. Just changing the parameters afterwards will not change the output.

This should work:
```python
@get_module
def sys_info(module):
    if module.format == "{nodename}":
        module.format = "{sysname} {release} on {machine}"
    else:
        module.format = "{nodename}"
    module.init()
```

**Comment by mr-ubik** [comment]
Thanks for the reply, I am still rather new to python and did not think about checking the module's code. However I would suggest to add this bit of of information to the docs.
