### ISSUE TITLE
{usage} doesn't work in Cpu_Usage_Graph

### ISSUE THREAD

**Issue by Orfby** [enkore/i3pystatus#417]
If I try to do `status.register("cpu_usage_graph", cpu="usage", format="{cpu_graph} {usage}%")`, in my i3status script, `CpuUsageGraph: 'usage'` is displayed in red, instead of the expected graph then percentage usage. If I remove the `{usage}` part however, it displays the graph as it should

**Comment by enkore** [comment]
Yeah that's a bug. Workaround: Use two modules side by side, cpu_usage and cpu_usage_graph.

**Comment by facetoe** [comment]
Should be all good now. Let me know if you get any more errors.
