### ISSUE TITLE
Bump minimum Python version?

### ISSUE THREAD

**Issue by enkore** [enkore/i3pystatus#430]
Currently i3pystatus requires (at least we assert that :) Python 3.2. A couple years ago when this was set that was reasonable, but by now Python 3.4 or 3.5 are pretty much the standard.

So, bump it? Is there a good reason (some major distro?) not to?

**Comment by facetoe** [comment]
No objection here.

**Comment by teto** [comment]
same. I use 3.5 wherever I can. I know python3.5 propose type hinitng
(which is why I use it) but what does python3.4 offer ?

2016-08-08 15:51 GMT+02:00 facetoe <notifications@github.com>:

**Comment by Arvedui** [comment]
[enum](https://docs.python.org/3/library/enum.html?highlight=enum#module-enum) and [asyncio](https://docs.python.org/3/library/asyncio.html?highlight=asyncio#module-asyncio) for instance. 
The complete list of  new major features can  be found[here](https://www.python.org/download/releases/3.4.0/).

**Comment by rumpelsepp** [comment]
Bump it to 3.5

**Comment by m45t3r** [comment]
asyncio support sure would be nice.

Ubuntu 14.04 already uses Python 3.4 anyway, and this is probably the oldest distro that people may still use in desktops. In worst case (someone using i3 in CentOS?), there is always: https://github.com/yyuu/pyenv.
