### ISSUE TITLE
disk module's critical_limit handling is broken

### ISSUE THREAD

**Issue by tomxtobin** [enkore/i3pystatus#433]
Recent commit 73dae9bfec7e16be4b9ad363700a9365e48695fe broke the `disk` module's handling of `critical limit` by reversing the comparison — at least for `avail`/`free` metrics, and `avail` is the default.

Perhaps the intention was to fix the handling for `used`, in which case you'd probably want a greater-than.

**Comment by facetoe** [comment]
Uhh sorry about that. It's kinda funny that the commit message is "Fix logic fail" when in fact it was introducing a logic fail...

I'll fix this up when I get home.
