### ISSUE TITLE
network module doesn't work if IPv6 is enabled on the system

### ISSUE THREAD

**Issue by mrshadowtux** [enkore/i3pystatus#437]
When IPv6 is activated on my system, I get the output
Network: invalid literal for int() with base 16: 'ffffffffffffffff/64' instead of the usual one.

I set up the module this way:
status.register("network",
	interface="wlp4s0",
	format_up=" {essid} {quality:3.0f}% ({v4cidr})",
	format_down=" WLAN aus",
	color_up="#FFFFFF",
	color_down="#A3A3A3",
)

Once IPv6 is disabled on my system via sysctl, the network module shows up the values just fine.

I'm running Arch Linux with the newest updates. If you need any logfiles drom me, please tell me.

Thanks in advance!

**Comment by enkore** [comment]
Did #435 fix this for you?

**Comment by mrshadowtux** [comment]
Yes, that solved it instantly. Thank you very very much for the quick fix!
