### ISSUE TITLE
Module 'Network': invalid option 'upper_limit'

### ISSUE THREAD

**Issue by andresmrm** [enkore/i3pystatus#438]
Getting this message on Network print:

    Module 'Network': invalid option 'upper_limit'

But 'upper_limit' setting is in the docs:
http://i3pystatus.readthedocs.io/en/latest/i3pystatus.html#network

Test code:

    from i3pystatus import Status
    from i3pystatus.network import Network

    status = Status(standalone=True)

    status.register(
            Network,
            interface="enp2s0",
            format_up="┃ {network_graph} {bytes_recv}   {bytes_sent}",
            format_down="",
            graph_width=5,
            upper_limit=4000,
            interval=3,
            divisor=1024*3,
    )

    status.run()

The error started today after I updated to git version from AUR (3.34.r248.g2eba2fd-1).
And I updated to git version because the other one started today to give another Network error about `int() ffffff...`

**Comment by facetoe** [comment]
This setting no longer exists in the git version, it has been replaced with `recv_limit` and `sent_limit` - https://github.com/enkore/i3pystatus/blob/master/i3pystatus/network.py#L277. I'm not sure what version the docs are tracking but it's probably the stable version.

You can fix this error by either removing or replacing `upper_limit` parameter.

**Comment by andresmrm** [comment]
Thanks! Solved!

Someone reported the `int() ffffff` error:
https://github.com/enkore/i3pystatus/issues/439

**Comment by enkore** [comment]
> I'm not sure what version the docs are tracking but it's probably the stable version.

Stale master. The webhook failed for some reason; I re-registered rtfd.io and it should now work. ie. on i3pystatus.rtfd.io stable = most recent release, latest = master branch.
