### ISSUE TITLE
Network: invalid literal for int() with base 16: 'ffffffffffffffff/64'

### ISSUE THREAD

**Issue by mihok** [enkore/i3pystatus#439]
Upgraded my machine last night to find in the morning this error.   [Screenshot](http://imgur.com/a/z6orQ)

Running:

Linux - 4.7.2-1 (Arch Linux 64x)
Python - 3.5.2

**Comment by andresmrm** [comment]
I can reproduce it even with this simple code:

    from i3pystatus import Status
    from i3pystatus.network import Network

    status = Status(standalone=True)

    status.register(
            Network,
            interface="enp2s0",
            format_up="",
            format_down="",
    )

    status.run()

Switching to git version from AUR solved it.

**Comment by hobarrera** [comment]
> Switching to git version from AUR solved it.

Sounds like we need a new release (I'm also having the same issue).

**Comment by enkore** [comment]
dup of #437; and yes new release soon. #440 is maybe related breakage.
