### ISSUE TITLE
Preferred way of logging

### ISSUE THREAD

**Issue by teto** [enkore/i3pystatus#456]
While creating a new module, I noticed several patterns for logging, with some doing
`from i3pystatus import logger` while others (abcradio.py) use `log = logging.getLogger(__name__)`.
I thin the correct way is the third one (self.logger.log), else the log_level parameter when registering a module is ignored. I think the doc can be clearer on this.

It would be nice if Status had a similar parameter, I currentl have a problem where after the first click, no click events is taken into account (only the first one) :/

**Comment by terminalmage** [comment]
abcradio.py should not need to use ``logging.getLogger()``. All of the base classes used by i3pystatus modules inherit a ``logger`` attribute.

Regarding the issue where click events aren't being logged, I think it's more than that. I have noticed that, depending on what happens in ``run()``, sometimes click events seem to stop being processed altogether. But I haven't had time to investigate the cause of this behavior.

**Comment by enkore** [comment]
Could be that the endpoint thread crashes if an exception is raised in run() in response to a click.

**Comment by teto** [comment]
How would I go to catch that ?
log = logging.getLogger("i3pystatus")
log.setLevel(logging.DEBUG)
Is there a way to enable DEBUG for all modules then ?


2016-09-22 0:42 GMT+02:00 enkore <notifications@github.com>:

**Comment by enkore** [comment]
By default a logger won't have a log level set. So the next higher up logger gets to say. Recursively. All loggers should have i3pystatus at their top. If that one has a log level but the others don't, then the i3pystatus logger level decides.

**Comment by richese** [comment]
@teto 
> Is there a way to enable DEBUG for all modules then ?

You can force debug by changing dafault `log_level` in SettingsBase.
```python
from i3pystatus.core.settings import SettingsBase
SettingsBase.log_level = 1
log = logging.getLogger("i3pystatus")
log.setLevel(1)
```
It could be added as a parameter to `Status`.

@enkore 
> By default a logger won't have a log level set. So the next higher up logger gets to say.

They seem to have [default log level](https://github.com/enkore/i3pystatus/blob/8d8c0b681247cc34711998759d30968325fa06ce/i3pystatus/core/settings.py#L108
) so I guess debug messages do not get passed to higher loggers even if  they have lower log level.
