### ISSUE TITLE
add support for rofication

### ISSUE THREAD

**Issue by teto** [enkore/i3pystatus#465]
Looks like cool stuff: https://github.com/DaveDavenport/Rofication, basically it stores notifications so that you can review them in one go after they popup

**Comment by enkore** [comment]
Should be simple enough: https://github.com/DaveDavenport/Rofication/blob/master/rofication-statusi3blocks.py

**Comment by teto** [comment]
Your comment encouraged me, current wip works: https://github.com/teto/i3pystatus/tree/rofication

**Comment by teto** [comment]
closing this as rofication doesn't seem to have a future according to its authors
