### ISSUE TITLE
i3pystatus-setting-util fails to load most modules

### ISSUE THREAD

**Issue by bel3atar** [enkore/i3pystatus#467]
When I run `i3pystatus-setting-util -v` I get:
i3pystatus-setting-util - part of i3pystatus
This allows you to edit keyring-protected settings of
i3pystatus modules, which are stored globally (independent
of your i3pystatus configuration) in your keyring.

Options:
    -l: list all stored settings (no values are printed)
    -v: print informational messages

ImportError while importing abc_radio
ImportError while importing alsa
ImportError while importing dota2wins
ImportError while importing github
ImportError while importing google_calendar
ImportError while importing gpu_mem
ImportError while importing gpu_temp
ImportError while importing iinet
ImportError while importing net_speed
ImportError while importing openstack_vms
ImportError while importing parcel
ImportError while importing reddit
ImportError while importing scratchpad
ImportError while importing sge
ImportError while importing spotify
ImportError while importing syncthing
ImportError while importing vk
ImportError while importing whosonlocation
ImportError while importing window_title
ImportError while importing zabbix
Choose a module to edit:
 1 - pyLoad
 2 - ModsDeChecker
 3 - MPD

**Comment by enkore** [comment]
Works as intended -- modules whose dependencies are not satisfied wouldn't work in i3pystatus either, but that shouldn't keep you from editing settings for working modules.

**Comment by bel3atar** [comment]
@enkore just noticed that 'mail' isn't on the list. I want to have the mail module get my credentials from the keyring. Is this possible?
