### ISSUE TITLE
Limit pulseaudio's max volume to 100%

### ISSUE THREAD

**Issue by bel3atar** [enkore/i3pystatus#469]
When triggering on_upscroll on pulseaudio, one can go above 100%.

**Comment by mankoell** [comment]
Why did you close this @bel3atar? I still have this issue with latest i3pystatus installed from AUR.

**Comment by bel3atar** [comment]
@mankoell it's a feature, not a bug

**Comment by tuliocasagrande** [comment]
@bel3atar can you elaborate how can this be a feature?

The [documentation](https://i3pystatus.readthedocs.io/en/latest/i3pystatus.html#module-i3pystatus.pulseaudio) says `{volume} — volume in percent (0...100)`.

**Comment by enkore** [comment]
Pulseaudio allows above-unity gain (volume >100%). So if a source is too low in volume it can be brought up by going above 100% channel volume. VLC is another popular application that allows this, for the same reason.

**Comment by tuliocasagrande** [comment]
hey @enkore, thank you for the prompt reply (and awesome library btw)!

I found it a bit confusing to see the volume going above 100% at first sight.
Do you think it is feasible (and of course desirable) to add a settings flag like **limit_max_volume** (default: `False`) or something?

I might be able to help on that.
