### ISSUE TITLE
clock module remains stuck when a big offset is applied

### ISSUE THREAD

**Issue by teto** [enkore/i3pystatus#493]
I ran a ntpdate which correct the offset by ~-3000 seconds, then the clock remained stuck and displayed the same time forever.
 5 Nov 17:27:55 ntpdate[14508]: step time server 2001:67c:1560:8003::c7 offset -3021.868977 sec

**Comment by hcpl** [comment]
This may be related to http://askubuntu.com/a/256004 and the issue is actually system-wide.
If not, can it be reproduced? What commands did you execute?
