### ISSUE TITLE
GPU module: ImportError(No module named 'i3pystatus.utils')

### ISSUE THREAD

**Issue by jcf** [enkore/i3pystatus#495]
Hello all,

I've been converting a few videos with GPU acceleration, and due to the recent issues with EVGA units overheating wanted to monitor my temperature.

I can do this from the command-line with `watch nvidia-smi -q -d temperature`, but can't create a module in my status bar because of an issue importing `i3pystatus.utils.`

![2016-11-06-21 35 18_1153x32](https://cloud.githubusercontent.com/assets/18374/20041930/f6362400-a468-11e6-8dd8-f41e50443cb9.png)

I'm running `i3pystatus-git 3.35.r81.ga9ff574-1`, and my i3pystatus config looks like this:

``` python
from i3pystatus import Status

status = Status(logfile='/var/log/jcf/i3pystatus.log',
                logformat='%(asctime) %(levelname)s:')

color_text = "#AAAAAA"

def smaller(s):
    return "<span size='smaller'>{}</span>".format(s)

status.register("clock",
                hints={"markup": "pango"},
                format=smaller("%a %d %b %H:%M"),
                on_leftclick="gnome-calendar")

status.register("alsa",
                hints={"markup": "pango"},
                format=smaller(" {volume:3.0f}/100"))

status.register("temp",
                hints={"markup": "pango"},
                format=smaller("{temp:.0f}°C"),
                on_leftclick="gnome-system-monitor --show-processes-tab")

status.register("cpu_usage",
                hints={"markup": "pango", "separator": False, "separator_block_width": 0},
                format=smaller(" {usage:3.0f}% "),
                on_leftclick="gnome-system-monitor --show-processes-tab")

status.register("gpu_temp",
                hints={"markup": "pango"},
                format=smaller(" {temp:.0f}°C"))

status.register("network",
                color_up=color_text,
                color_down=color_text,
                # divisor=2**20,
                dynamic_color=False,
                hints={"markup": "pango"},
                format_up=smaller(" {bytes_recv:5.0f} KB/s   {bytes_sent:5.0f} KB/s"),
                interface="eno1",
                on_leftclick="gnome-system-monitor --show-resources-tab")

status.run()
```

I'm guessing the issue is with importing `.utils`, but I'm not super experienced with Python…

**Comment by jcf** [comment]
Oh, and massive thank you for #491!

**Comment by jcf** [comment]
Also, does anyone know why left padding a float appears to emit fewer spaces than I've requested? With my upload/download I want a five column width but get less than that.

**Comment by enkore** [comment]
Perhaps Pango interprets whitespace like HTML, ie. adjacent whitespace is collapsed into a single space. Maybe wrapping it in `<tt>text</tt>` helps?

**Comment by jcf** [comment]
> Perhaps Pango interprets whitespace like HTML

@enkore looks like that's the issue. Unfortunately, rendering as text as "monospace" messes with font rendering making things look broken.

![2016-11-08-14 51 13_533x32](https://cloud.githubusercontent.com/assets/18374/20103704/f3319022-a5c2-11e6-83c1-b4278d177f24.png)

Notice the 100 before the slash in my volume module is larger than it should be. I can't find any answers on https://developer.gnome.org/pygtk/stable/ either. I guess I'll just have to look into Pango some more.

Thanks!

**Comment by jcf** [comment]
@enkore any ideas why the GPU temp module doesn't work?

**Comment by enkore** [comment]
No, but maybe @PolarNick239 or @drwahl have an idea

**Comment by PolarNick239** [comment]
Hm, this is my bug - I added i3pystatus.utils package, but didn't add it to [setup.py here](https://github.com/enkore/i3pystatus/blob/master/setup.py#L18-L26).
You can locally checkout sources and add there `"i3pystatus.utils",` line and than install it via `pip install -e i3pystatus`, where i3pystatus - directory with `git checkout` sources.

I will make pull request with fix when will have time to check this fix. (probably in a couple of days)

**Comment by enkore** [comment]
Ah, thanks that makes a lot of sense. I made a PR which should fix this #497

**Comment by jcf** [comment]
Thanks, @PolarNick239, @enkore.

**Comment by jcf** [comment]
The GPU module loads, and returns a different error now.

![2016-11-16-18 45 07-717x29-be762f3901e1](https://cloud.githubusercontent.com/assets/18374/20360749/d0033f54-ac2c-11e6-9c84-67a844668054.png)

```
GPUTemperature: TypeError: eval() arg 1 must be a string, bytes or code object
```

**Comment by enkore** [comment]
Can you check `~/.i3pystatus-<pid>`, there should be by default logs there iirc

**Comment by jcf** [comment]
@enkore log output:

```
%(levelname)s:
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/i3pystatus/core/threading.py", line 68, in __call__
    self.workload()
  File "/usr/lib/python3.5/site-packages/i3pystatus/core/modules.py", line 285, in __call__
    self.run()
  File "/usr/lib/python3.5/site-packages/i3pystatus/gpu_temp.py", line 33, in run
    if eval(self.display_if):
TypeError: eval() arg 1 must be a string, bytes or code object
```

**Comment by hcpl** [comment]
Removing eval() should fix this.

**Comment by jcf** [comment]
@hcpi is it [this eval](https://github.com/enkore/i3pystatus/blob/cc3781a6c01c7c4e7a11044ef2382825b7c58674/i3pystatus/gpu_temp.py#L33) that's the problem?

**Comment by hcpl** [comment]
@jcf it should be, but I can't check (I don't have an Nvidia).

**Comment by jcf** [comment]
@hcpl ah, of course! I tried `true` at first obviously forgetting that Python uses a capitalised `True`. I'll move to the simpler literal `True` later today.

I'd think it makes sense to only `eval` when `self.display_if` is not null. Out of interest, is use of `eval` not frowned upon in Python?

Closing as this issue has been fixed.
