### ISSUE TITLE
DNF Updates module always displays "Updates: 0"

### ISSUE THREAD

**Issue by CPrompt** [enkore/i3pystatus#498]
Running Fedora 25
all other modules seem to be working fine.
DNF Update always displays "Updates: 0"
Here is the updates section from my config file:

status.register("updates",
                        format = "Updates: {count}",
                        color = "#689d6a",
                        color = "#00DD00",,
                        format_no_updates = "No updates",
                        color_no_updates = "#ebdbb2",
                        format_working = None,
                        color_working = None,
                        backends = [dnf.Dnf()],)

Thanks!

**Comment by hcpl** [comment]
@CPrompt, perhaps the problem lies in [this line](https://github.com/enkore/i3pystatus/blob/master/i3pystatus/updates/dnf.py#L38). Now `updates` calls the generic `Backend().updates` which always equals to `0`:
```python
print("Updates: {}\n\n{}".format(*Backend().updates))
```
but `Dnf` should be used instead:
```python
print("Updates: {}\n\n{}".format(*Dnf().updates))
```

**Comment by terminalmage** [comment]
I just submitted a pull request that rewrites the dnf update checker so that it uses the DNF Python API.

https://github.com/enkore/i3pystatus/pull/499

**Comment by CPrompt** [comment]
Thanks!  I did test this and it does work.

Thanks!!

**Comment by terminalmage** [comment]
@CPrompt Great, thanks for testing! It's still under discussion in the comments of the PR thread so it hasn't been merged, but we'll get it figured out.
