### ISSUE TITLE
Inconsistent return value types for update backends

### ISSUE THREAD

**Issue by jotasi** [enkore/i3pystatus#504]
When trying to add a new backend to check for updates, I noticed that the return value types are inconsistent across different update backends, leading to breakage of the DesktopNotification in the report method for some of the backends.

While all backends return a number of updates, the listing of the available updates is one string containing one update per line for the backends `cower`, `dnf`, and `pacman`. `aptget` on the other hand returns a list of one line strings. `yaourt` seems to be even inconsistent with itself, returning a string, when `aur_only=False` and a list otherwise. The problem with this is, that `"\n".join(self.notif_body.values())` in line 156 of `i3pystatus/updates/__init__.py` fails for backends that return a list, as `self.notif_body.values()` is then a list of list rather than a list of strings.

I would be happy to submit a pull request cleaning this up, but I first wanted to clarify, which return value is considered correct. As most backends return a string, I'd guess, that this is the way to go. Is this correct?

**Comment by enkore** [comment]
Fixed by#507
