### ISSUE TITLE
Bug in yaourt update backend

### ISSUE THREAD

**Issue by jotasi** [enkore/i3pystatus#505]
When looking into the issue I described in #504, it seemed to me that actually the case of `self.aur_only=True` is actually completely broken. For that case, the output of the shell command (which is a `string`) is parsed using:

    if(self.aur_only):
        out = [line for line in out if line.startswith("aur")]

But as far as I can see, this will always result in an empty `out`, as this will iterate out character by character rather than line by line and thus the condition `line.startswith("aur")` will never be met. I'll submit a pull request fixing this and #504 today.

**Comment by enkore** [comment]
Fixed by #506
