### ISSUE TITLE
display multiple clocks with different timezone

### ISSUE THREAD

**Issue by 2Belette** [enkore/i3pystatus#508]
I am trying something like this to display multiple clocks with different timezone.
`format = [ ('%a %b %-d %b %X', 'America/New_York'), ('%X', 'Etc/GMT+9') ]`
This only show one clock, is it expected?
Not able to make it work, for now I am only able to use two status.register("clock") sections but I don't want the separator between the clocks so I would prefer to be get both clocks on the same register section

**Comment by terminalmage** [comment]
When you specify multiple formats, only one is displayed at a time, and using mouse/trackpad scrolling on the clock module will cycle between the different timezones. There is no way to display multiple timezones at the same time in the same registered instance.

This is documented [here](http://i3pystatus.readthedocs.io/en/latest/i3pystatus.html#module-i3pystatus.clock), FWIW.

**Comment by 2Belette** [comment]
Thanks
Yep this is where I picked the example, now it makes sense so I have to use my trick

**Comment by terminalmage** [comment]
No prob!

**Comment by richese** [comment]
@2Belette 
You can hide the separator between two modules with `hints` setting to get two instances of clock to look like one module. Add `hints = {"separator": False, "separator_block_width": 0}` to one of the modules and you should be good to go.
[Hints documentation](http://i3pystatus.readthedocs.io/en/latest/configuration.html#hints)

**Comment by terminalmage** [comment]
@richese good point. wouldn't that need to be done specifically to the 2nd ``clock`` instance? If I understand correctly the separator is placed to the right of the module, and modules are filled in from right to left.

**Comment by richese** [comment]
@terminalmage 
Yes, that's how it should work. And maybe a non-zero `separator_block_width` to keep the outputs visually separated since most modules strip trailing spaces from their outputs.
