### ISSUE TITLE
vpn module does not detect OpenVPN 2.4 systemd units

### ISSUE THREAD

**Issue by lunik1** [enkore/i3pystatus#515]
In OpenVPN 2.4 the `openvpn@.service` was split into `openvpn-client@.service `and `openvpn-server@.service`. Currently the module only looks for  `openvpn@.service`, so will always display as disconnected if OpenVPN 2.4 is being used.

**Comment by terminalmage** [comment]
You should in the meantime be able to set your own ``vpn_up_command`` and ``vpn_down_command``, just FYI.

**Comment by terminalmage** [comment]
Also, ``status_command``.

**Comment by facetoe** [comment]
As @terminalmage mentions, you can alter the `status_command` variable to correctly detect the state in the new format.

I've just upgraded and have the same issue, however I don't think it's worth changing the module as it will break it for everyone else.

**Comment by terminalmage** [comment]
@facetoe I just opened https://github.com/enkore/i3pystatus/pull/518 to add some documentation for others that might run into this issue.

**Comment by facetoe** [comment]
Awesome good idea.

**Comment by enkore** [comment]
Fixed in #518
