### ISSUE TITLE
pypi problems

### ISSUE THREAD

**Issue by tobes** [enkore/i3pystatus#536]
1) a python2 version of i3pystatus is available but is broken due to import issues

2) i3pystatus-3.35 appears to be incomplete eg `i3pystatus.utils` is not present

**Comment by enkore** [comment]
Thanks for the report.

Python 2 hasn't been supported for years.

Yes, that release was incomplete (duplicate of #495), a fixed is committed but not released yet.

**Comment by tobes** [comment]
> Python 2 hasn't been supported for years.

So you should remove it from pypi then :)

**Comment by enkore** [comment]
Can you point me to where you found the Python 2 reference?

**Comment by tobes** [comment]
`python2 -m pip install i3pystatus` installs a non-working version

I think you want a `Requires-Python: >= 3.2` see https://www.python.org/dev/peps/pep-0345/#requires-python  It might be more of a pypi/pip issue

**Comment by enkore** [comment]
Ah, I see. I thought giving it the `Python :: 3` trove qualifier but not `Python :: 2` was sufficient.
