### ISSUE TITLE
battery notification timeout too short

### ISSUE THREAD

**Issue by kyrias** [enkore/i3pystatus#549]
60 ms is really too short to read the notification, and it blinking over and over will both increase the power usage, and are also rather annoying.  Could we increase this to a minute or so instead, and if the user wants it to blink they could have their notification daemon take care of that?

**Comment by enkore** [comment]
Should've probably been 60 seconds

**Comment by kyrias** [comment]
Honestly, it would probably make sense to have it as a module setting and have the default just be the server default instead.
