### ISSUE TITLE
Module 'Shell': invalid option 'ignore_empty_stdout'

### ISSUE THREAD

**Issue by dbkblk** [enkore/i3pystatus#553]
Hi,

I try to set up a custom script using the shell module, but the following message is returned in the bar when I try to use the option to hide output on empty echo:
`Module 'Shell': invalid option 'ignore_empty_stdout'`

The code is as follows:
```python
status.register(
    shell',
    command='/home/hadrien/Dropbox/config/scripts/bars/gmail.sh',
    ignore_empty_stdout=True,
    interval=60,
    color="#FFFFFF",
    on_leftclick='firefox https://mail.google.com/mail/u/0/#inbox'
)
```

I have followed the instructions in [the documentation](https://i3pystatus.readthedocs.io/en/latest/i3pystatus.html#module-i3pystatus.shell) and even checked the code. I don't get what's wrong there.

**Comment by richese** [comment]
Works for me. Do you have the latest version of i3pystatus from git? This feature was added to git on 25. Dec. 2016 but current _stable_ release (3.35) is from 31. Aug. 2016.

**Comment by dbkblk** [comment]
Oh, no. Indeed, it works with the latest git version.
Many thanks for your software, it is awesome!
