### ISSUE TITLE
Spotify doesn't clear bar and requires i3 restart on exit to refresh data

### ISSUE THREAD

**Issue by firecat53** [enkore/i3pystatus#554]
I have to restart i3 to refresh the bar and clear the Spotify data after I shut it down. If I don't restart i3, the data stays and won't refresh even if Spotify is started again. I'm using latest git version of i3pystatus.

My $HOME/.config/i3/status.py:

    status.register("spotify", format="{status} {title:<.35} - {artist:<.20}")

I stepped through the code in ipython and it seems to be registering the lack of a player correctly, but for some reason after the `raise NoPlayerException` in now_playing.py, that block stops updating.

Thanks!
Scott

**Comment by m45t3r** [comment]
I can confirm some issues in the current code for Spotify. The bug that OP described (exiting from Spotify needs a restart from i3pystatus or the bar is not updated anymore), and sometimes I get a "NowPlaying: KeyError: None" (that I find strange, since there is a catch for this Exception in the code).

Will try to investigate when I have some free time.

**Comment by firecat53** [comment]
Well, what's odd is that after awhile it started working again. I had troubles with it for several weeks. About a week after I submitted the issue it started working correctly and has been ever since. I left the issue open in case it came back. Perhaps @m45t3r will be able to track it down. Thanks!

**Comment by firecat53** [comment]
Haven't had a problem...in a year now apparently! Closing

**Comment by AnyTimeTraveler** [comment]
I'm having this issue again.
This time it is consistent, whenever there is no media player running, it displays "NowPlaying: KeyError: None".
This is happening for a while now, but I wasn't bothered by it until I reinstalled today and was getting my i3 setup again.

This is how I am registering the module:
```
status.register("now_playing",
                format="  {status} {title} - {album} - {artist}",
                format_no_player="  {status}",
                status={
                    "pause": "",
                    "play": "",
                    "stop": "",
                },)
```

I am using Spotify and VLC and whenever one of them is running, it works as intended.
