### ISSUE TITLE
cannot import name Timer

### ISSUE THREAD

**Issue by stephane-archer** [enkore/i3pystatus#556]
I have the following error:

`  File "/usr/local/lib/python2.7/dist-packages/i3pystatus/core/util.py", line 7, in <module>
    from threading import Timer, RLock
ImportError: cannot import name Timer
`

I'm on ubuntu.

How to solve the problem? :)

**Comment by richese** [comment]
You seem to be using python2.7. i3pystatus requires python3.

**Comment by stephane-archer** [comment]
thank you :)

So the command line to install is:
`pip3 install i3pystatus`
