### ISSUE TITLE
Weather plugin error : 'Unable to parse api_key from forcast page'

### ISSUE THREAD

**Issue by CPrompt** [enkore/i3pystatus#557]
Status line only shows "Error: status_command process exited unexpectedly (exit 1)' which I think is just a generic error?

I ran the config itself and got 

File "/usr/lib/python3.5/site-packages/i3pystatus/weather/weathercom.py", line 189, in init
    'Unable to parse %s from forecast page' % attr)
RuntimeError: Unable to parse api_key from forecast page

I have logging turned on but it doesn't seem to logging any information.  No logfile is created.

**Comment by terminalmage** [comment]
OK, weather.com may have changed their API a bit. I'll take a look.

**Comment by terminalmage** [comment]
@CPrompt https://github.com/enkore/i3pystatus/pull/558

**Comment by terminalmage** [comment]
Also https://github.com/enkore/i3pystatus/pull/559
