### ISSUE TITLE
Show different string in network module depending on active interface type

### ISSUE THREAD

**Issue by rscholer** [enkore/i3pystatus#564]
I'm testing the new "detect_active" function in the network module.

What I would like to do is to print "Ethernet" when my ethernet connection is active, and "Wifi", when my wireless connection is active.

Can this already be done, or is it necessary to implement this functionality in the module?

**Comment by facetoe** [comment]
This may be possible using the [callback](https://i3pystatus.readthedocs.io/en/latest/configuration.html#callbacks) functionality. If you know the name of your Ethernet and Wifi interfaces you could probably write a Python function to modify the output accordingly. If this is a feature that people want it would also be easy to add a a configurable mapping to the module.
