### ISSUE TITLE
Accurate Clock

### ISSUE THREAD

**Issue by GRMrGecko** [enkore/i3pystatus#566]
The one thing that bugs me the most with many i3 status replacements, is that nothing is able to provide a clock which is accurate on seconds. I personally enjoy having accurate time, but do not know how to get this with i3. I have attempted to add the following to the beginning of the run function in clock.py, however it appears that it has to also wait on other modules to update data before being pushed out to the screen.
```python
time.sleep(1.002-(time.time()%1))
```
If you can help me get accurate time, I would highly appreciate it.

Thank you

**Comment by chestm007** [comment]
Its a bit late but i feel like this should serve your purpose:

```
status.register(                      
    "clock",                          
    format="%d/%m  %H:%M:%S",         
    color='#C678DD',                  
    interval=0.5,                     
    on_leftclick="/usr/bin/gsimplecal"
)                                     
```

the key setting being `interval` this determines how often the module should refresh

**Comment by GRMrGecko** [comment]
My current setting is

```
status.register("clock",
                format="%a %b %-d %l:%M:%S %P",
                interval=0.5)
```

However, if you visit https://time.is/ and compare the current accurate time to the i3pystatus time, you will see that the seconds are typically off even if the real time clock is right on your system. I'm looking to get the seconds accurate.

**Comment by GRMrGecko** [comment]
Thanks for the information, that does the trick. I adjusted the interval to about 0.3 which utilizes about 1% of my CPU.
