### ISSUE TITLE
can't show cpu_usage

### ISSUE THREAD

**Issue by leo-mao** [enkore/i3pystatus#570]
Hello,
i3pystatus can't run correctly, in the cpu usage field remains `usage: Missing Python module 'i3pystatus.usage'`, and I tried to `from i3pystatus import Usage`, but the interpreter complained.
And I tried search through the documentations, there is no clear hint about the "module" to be import.
Could someone help me?
Best Wishes
Mao

**Comment by facetoe** [comment]
The module is named cpu_usage, not usage.

**Comment by leo-mao** [comment]
@facetoe but `from i3pystatus import cpu_usage` also doesn't help.

**Comment by facetoe** [comment]
You don't need to import it, you just need to register it in your config. Can you post the section where you register the cpu_usage module?

**Comment by leo-mao** [comment]
here is it

> # CPU usage
status.register("usage",
        format=" {usage}%",)

**Comment by facetoe** [comment]
Yep, should be:

    status.register("cpu_usage",
    ...

**Comment by leo-mao** [comment]
Great, it works like a charm.
so the second segment in class name is the module I always need to register `class i3pystatus.cpu_usage.CpuUsage`, right?

**Comment by facetoe** [comment]
Yep, you got it

**Comment by leo-mao** [comment]
Thanks a lot for your kindness:)
Mao



On Sat, May 13, 2017 at 3:47 PM +0200, "Facetoe" <notifications@github.com<mailto:notifications@github.com>> wrote:


Yep, you got it
