### ISSUE TITLE
Multi-core temperature example is giving errors: invalid options 'dynamic color' and 'lm_sensors_enabled'

### ISSUE THREAD

**Issue by fusion809** [enkore/i3pystatus#575]
Hi,

I copied this example from the [docs](http://i3pystatus.readthedocs.io/en/latest/i3pystatus.html#module-i3pystatus.temp) to my config script:

```python
# Shows your CPU temperature, if you have a Intel CPU
status.register("temp",
    format="{Physical_id_0}°C {Core_0_bar}{Core_1_bar}{Core_2_bar}{Core_3_bar}",
    hints={"markup": "pango"},
    lm_sensors_enabled=True,
    dynamic_color=True)
```
and I think this screenshot shows you the problem quite well:

![screenshot_20170610_105628](https://user-images.githubusercontent.com/4717341/26998755-0f86e464-4dcc-11e7-827d-d12fb21cab2b.png)

Thanks for your time,
Brenton

**Comment by fusion809** [comment]
Oops the docs has a graphical glitch so I missed the extra dep, you can see the glitch in this screenshot:

![screenshot_20170610_121517-cropped](https://user-images.githubusercontent.com/4717341/26999172-b82100c8-4dd6-11e7-81af-3c51cf79e1ff.png)

I installed it though and still the same error.

**Comment by enkore** [comment]
My bad about that docs glitch

```
#module-reference dl.class dd {
    margin-top: -1.5em;
}
```

**Comment by facetoe** [comment]
Are you using the latest version of i3pystatus from master? If you are using an older version that would explain the errors relating to `dynamic_color` and `lm_sensors_enabled`.

**Comment by fusion809** [comment]
I've given master and the latest tag release a go, with both I got these errors.

**Comment by facetoe** [comment]
Hmm, the example above works for me. Are you sure you aren't executing an older version of i3pystatus? Can you try uninstalling all versions of i3pystatus (`locate i3pystatus | grep -v $HOME` should return nothing) and then running the latest code from master?

**Comment by fusion809** [comment]
Aha you were right, I had a system and local install of i3pystatus the local was the latest tagged release and the system was the master one. Sorry, but now I'm getting a different error:

![screenshot_20170612_142123](https://user-images.githubusercontent.com/4717341/27019288-7a611a5c-4f7a-11e7-8834-4c1fa52a17e4.png)

the temperature one is just one of two errors I see. I don't live in a furnace so it's not 77&deg;C 'ere it's actually just 25&deg;C 'ere (per #577).

**Comment by facetoe** [comment]
The format keys for sensors are system specific. See the section `lm_sensors_mode formatters` in the documentation for the `temp` module for information on how to discover the correct keys for your system.

**Comment by fusion809** [comment]
I shall close this issue then, thanks.
