### ISSUE TITLE
Divisor for RAM error: unsupported operand type(s) for /: 'int' and 'str'

### ISSUE THREAD

**Issue by fusion809** [enkore/i3pystatus#576]
Hi,

I've added this to my i3 Python config script:

```python
status.register("mem", 
    format="RAM: {used_mem} {total_mem}", 
    color="#FFFFFF", 
    divisor="1073741824")
```

Originally I had:

```python
status.register("mem", 
    format="RAM: {used_mem} GiB / {total_mem} GiB", 
    color="#FFFFFF", 
    divisor="1024**3")
```

but in my own efforts to try to fix this I removed the units and `/` in the `format` field and converted the divisor from a mathematical expression to just a numerical value. psutil is installed. Version of i3pystatus is 3.35 and psutil version is 5.2.2. The version of Python being used is 3.4.6. 

Thanks for your time,
Brenton

**Comment by Arvedui** [comment]
The divisor option must be a number, not a string. Remove the quotes around 1024**3.

**Comment by fusion809** [comment]
Thanks, sorry didn't think it'd be that trivial.
