### ISSUE TITLE
Weather data is inaccurate: seems like degrees F and C are being confused with one another

### ISSUE THREAD

**Issue by fusion809** [enkore/i3pystatus#577]
Hi,

I have this in my config script:

```python
status.register(
    'weather',
    format='{condition} {current_temp}{temp_unit}',
    colorize=True,
    hints={'markup': 'pango'},
    backend=weathercom.Weathercom(
        location_code='ASXX0117:1:AS',
        units='metric',
    ),
)
```

and it's giving a ridiculously high temperature of 70&deg;C even though in the place this location code pertains to (Townsville, Australia) the temperature is shown [here](https://weather.com/en-AU/weather/today/l/ASXX0117:1:AS) as just 21&deg;C at this point of time. My config script is [here](https://pastebin.com/K2FdHr3f). 

Thanks for your time,
Brenton

**Comment by fusion809** [comment]
Hmm this issue seems to only occur sometimes not all the time. Now it's back to saying "Fair 22&deg;C".

**Comment by facetoe** [comment]
It doesn't look like the module does any conversion between fahrenheit and celcius.

Do you still get the results in fahrenheit?

**Comment by fusion809** [comment]
Sure do. Getting it right now, here's a screenshot:

![screenshot_20170612_200726](https://user-images.githubusercontent.com/4717341/27029240-ccd6f768-4faa-11e7-8a4a-d06a3498a13b.png)

**Comment by facetoe** [comment]
How often have you seen it correctly reporting Celcius?

**Comment by fusion809** [comment]
If I had to hazard a guess I'd say about half, maybe less of the time I've run i3pystatus. I switch between i3pystatus and C/C++/Shell-based i3 config.

**Comment by facetoe** [comment]
Can you test #582 and see if it resolves your issue? You will need to modify your config as follows:

```python
status.register(
    'weather',
    format='{condition} {current_temp}{temp_unit}',
    colorize=True,
    hints={'markup': 'pango'},
    backend=Weathercom(
        location_code='ASXX0117:1:AS',
        locale='en-AU',
        units='metric',
    ),
)
```

**Comment by fusion809** [comment]
Well I'll be, it works! Thanks

**Comment by facetoe** [comment]
No worries. I'll merge the PR in a few days to give others time to comment.
