### ISSUE TITLE
RAM usage is occasionally represented as a negative value

### ISSUE THREAD

**Issue by fusion809** [enkore/i3pystatus#580]
Hi,

With this i3pystatus mem config:

```python
status.register("mem", 
    format="RAM: {used_mem}/{total_mem} GiB", 
    color="#FFFFFF", 
    divisor=1073741824
    )
```

I get negative values for RAM usage in my i3status bar. Here is a screenshot to show it (I've circled or rather rectangled around it in red to point it out):
![negmem-i3pystatus-redcirc](https://user-images.githubusercontent.com/4717341/27008437-3f94958c-4eb4-11e7-93c1-d79416f828ec.png)

I have tried to fix this myself by throwing abs around the RHS of [L48](https://github.com/enkore/i3pystatus/blob/master/i3pystatus/mem.py#L48) and [L50](https://github.com/enkore/i3pystatus/blob/master/i3pystatus/mem.py#L50) of the mem.py file. It made no difference I'm afraid. This issue is intermittent, by-the-way, when I've just booted my system after several hours of it being off the issue is not there but after the system has been up for several hours the issue is there. Any ideas on how to fix this issue?

Thanks for your time,
Brenton

**Comment by hasB4K** [comment]
Hi @fusion809,

I'm not sure that will help, but why your divisor is equal to `1024 ** 3` (1073741824) instead of `1024 ** 2` (1048576) to represent GiB?
Also, what is your version of psutil?

Regards,

**Comment by fusion809** [comment]
I'm using `1024 ** 3` because my system has heaps of RAM so GB is a more easy unit to use, at least IMO. psutil version is 5.2.2.

**Comment by hasB4K** [comment]
Ok, this is very odd, I never experienced that issue before, even though I use i3pystatus on a daily basis. I decided to upgrade my version of psutil from 5.1.3 to 5.2.2 to check if I experience the bug. I suspect a regression on psutil...
Maybe you could downgrade yours to 5.1.3 to see if you experiment the bug in that case?

**Comment by hasB4K** [comment]
Also, you said that the issue is intermittent. What is the average ratio when it works and when it does not?

**Comment by fusion809** [comment]
Ratio: &ge;2:1.

I downgraded, the problem is no matter how long I use this for I can't say for certain it's gone because this issue is intermittent.

**Comment by enkore** [comment]
When it happens, take a look at free(1) and see whether you can somehow arrive at the negative number from there. (used-cache maybe?)

**Comment by fusion809** [comment]
Still no issues despite constant usage so it might seem to be fixed but as I said when this issue does it occur it does so randomly and intermittently so there's no way to know for certain whether it's truly gone. Another couple of days without this issue and I'll be confident enough to announce that psutil 5.2.2 was probably the issue.

**Comment by hasB4K** [comment]
I didn't see any errors for now on my side, I will keep that version to see if there any change in the coming days anyway.
What OS version are you using?

**Comment by fusion809** [comment]
The wallpaper says it all: Gentoo Linux. It has no version as it's a rolling release distribution.

**Comment by fusion809** [comment]
Been two days and no switch over yet, might be resolved...

**Comment by vidister** [comment]
I'm having the same problem with Arch Linux and psutil 5.4.3.

**Comment by chestm007** [comment]
Is this still an issue?

**Comment by lasers** [comment]
```python3
>>> -4509715660.8 / (1024 ** 3)
-4.2  # GiB
```
I don't see how it can be an issue with `mem` module. The values comes from `psutil`. https://psutil.readthedocs.io/en/latest/#memory

I wanted to know if `mem` should keep printing occasional negative values or do we replace occasional negative values with `0` to make it easier for users? (i.e. hide negative values from users)

If you like https://github.com/lasers/i3pystatus/commit/ea46f44d4bf8bb9bcac043ae34a4ff583978b220, I can make a PR.
