### ISSUE TITLE
network field of the bar is hidden when format= option is specified

### ISSUE THREAD

**Issue by fusion809** [enkore/i3pystatus#583]
Hi,

I'm using the git master version of i3pystatus with Python 3.4.6 and if the `format=` option isn't specified to the network field of i3pystatus it is shown without issue in the i3bar. If this field *is* specified, even if it is just the default value of this field, the network field isn't shown in the i3bar. For example, this is what I see with `status.register("network", interface="wlo1", format="{interface} {network_graph}{kbs}KB/s")` in my config file:

![screenshot_20170612_235914](https://user-images.githubusercontent.com/4717341/27037448-57e1c48a-4fcb-11e7-9d40-f248c62bc78b.png)

while this is what I see with `status.register("network", interface="wlo1")` in my config file:

![screenshot_20170613_000228](https://user-images.githubusercontent.com/4717341/27037531-a390e046-4fcb-11e7-9811-8477dc40fd0a.png)

Guessing there's some issue with parsing the `format=` option. This issue occurs even if I change the `format=` option to `format="{bytes_recv} kB/s"` or other values, so it isn't just for `format="{interface} {network_graph}{kbs}KB/s"`.

Thanks for your time,
Brenton

**Comment by facetoe** [comment]
As per the documentation for the network module (https://i3pystatus.readthedocs.io/en/latest/i3pystatus.html#network), you should use `format_up`, not `format`.

**Comment by fusion809** [comment]
Ah sorry shall close.
