### ISSUE TITLE
Project status, planned releases and governance

### ISSUE THREAD

**Issue by enkore** [enkore/i3pystatus#584]
https://github.com/enkore/i3pystatus/compare/b04f9b733299ddfec336...master

I just wrote down what I think is the status quo.

**Comment by hobarrera** [comment]
Why the decision for now-more releases (even though development moves on)?

A huge downside of this, is that distribution packages will be forever frozen with the last (ageing) release. Users that install via their distributions repositories will never-again see an update (only those that install from manually from source).

**Comment by terminalmage** [comment]
Perhaps it would be a good idea to add some documentation on installing into (and running from) a virtualenv? I have a `pip --editable` installation pointing at a git worktree, allowing me to rapidly test changes to the project. This approach seems to work well for me, and running i3pystatus from the virtualenv is easy, as one only needs to call the `python` executable within the virtualenv to get the virtualenv into the pythonpath:

```
bar {
    status_command /home/erik/virtualenv/i3pystatus/bin/python /home/erik/.config/i3/status.py
}
```

An approach like this would allow for people to keep up-to-date if they wish, while allowing for the occasional release for those that prefer installing from their distro's package repository.

**Comment by enkore** [comment]
> Why the decision for now-more releases (even though development moves on)?

- Releases require time to prepare
- Most modules don't have tests or can't be meaningfully tested anyway, so there is no stability advantage to releases

**Comment by hobarrera** [comment]
How should downstream packagers deal with that? Always package the latest release?

**Comment by lasers** [comment]
Can we close this?
