### ISSUE TITLE
Errors on Arch Linux with Python 3.6: KeyError 'locale'

### ISSUE THREAD

**Issue by fusion809** [enkore/i3pystatus#588]
I recently took my Gentoo (using Python 3.4) [i3pystatus configs](https://github.com/fusion809/i3-configs) to Arch Linux where Python 3.6 is in use and I noticed that i3pystatus was throwing an exception leading to the classic error in the i3 bar: 

"Error: status_command process exited unexpectedly (exit 1)". 

I then ran the main i3pystatus script [`i3status.py`](https://github.com/fusion809/i3-configs/blob/master/.i3/i3status.py) from the Linux command-line and I got the error:

```python
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/i3pystatus/core/settings.py", line 94, in __init__
    sm.update(settings_source)
  File "/usr/lib/python3.6/_collections_abc.py", line 841, in update
    self[key] = other[key]
  File "/usr/lib/python3.6/site-packages/i3pystatus/core/util.py", line 111, in __setitem__
    raise KeyError(key)
KeyError: 'locale'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./i3status.py", line 47, in <module>
    units="metric",
  File "/usr/lib/python3.6/site-packages/i3pystatus/core/settings.py", line 96, in __init__
    raise ConfigKeyError(type(self).__name__, key=exc.args[0]) from exc
i3pystatus.core.exceptions.ConfigKeyError: "Module 'Weathercom': invalid option 'locale'"
```

The way I installed i3pystatus was with:

```bash
sudo pip3 install https://github.com/enkore/i3pystatus/archive/master.tar.gz
```

Just so you know I'm using the master branch of this repo and not the latest tagged release 3.35.

**Comment by enkore** [comment]
I think the locale option was removed

**Comment by facetoe** [comment]
Yep, it was both added and removed in #582.

**Comment by fusion809** [comment]
Oh darn because in #577 I was advised to use it in order to fix a switch up between degrees Celsius and Fahrenheit.

**Comment by facetoe** [comment]
Yep, my bad, I never let you know the option changed. Apologies!

**Comment by fusion809** [comment]
'tis fine I should have followed ya pull request.

**Comment by facetoe** [comment]
All good!
