### ISSUE TITLE
Battery status symbols depending on percentage

### ISSUE THREAD

**Issue by dotlambda** [enkore/i3pystatus#591]
Is it possible to set the battery status depending on the percentage?
If the battery is discharging, I want to have four different icons (for <=25, <=50, <=75 and <=100%).
In the docs, I didn't find a way to set the status using a custom python function.

**Comment by drwahl** [comment]
The battery module can currently only change the icon/status when full, critical, and charging.  I guess the module could be updated to support percentage based icons, but that would require a bit of tweaking.

**Comment by dmelliot** [comment]
Hi,
Not sure if either of you are still interested given above discussion is over a year ago, but I've just raised a PR which should (mostly) meet this feature request.

Ref: https://github.com/enkore/i3pystatus/pull/674
