### ISSUE TITLE
Feature request: Add the ability to include shell output in i3bar managed by i3pystatus

### ISSUE THREAD

**Issue by fusion809** [enkore/i3pystatus#593]
Hi,

I'd like to request the ability to add shell script output to the i3bar, when the i3bar is managed by i3pystatus. For example, at the moment I have this script:

```bash
cd $HOME/OBS/home:fusion809/vim
pkgver=$(wget -q https://github.com/vim/vim/releases -O - | grep "tar\.gz" | head -n 1 | cut -d '/' -f 5 | cut -d '"' -f 1 | sed 's/v//g' | sed 's/\.tar\.gz//g')
baseversion=$(echo $pkgver | sed 's/\.[0-9]*$//g')
patchversion=$(echo $pkgver | sed "s/$baseversion//g" | sed 's/\.//g')
vim_baseversion=$(cat vim.spec | grep "%define.*baseversion" | sed 's/%define.*baseversion\s*//g' | head -n 1)
vim_patchversion=$(cat vim.spec | grep "%define.*patchlevel" | sed 's/%define.*patchlevel\s*//g' | head -n 1)
if [[ $pkgver = ${vim_baseversion}.${vim_patchversion} ]]; then
     printf "Vim is up-to-date.\n"
else
     printf "New Vim is available: $pkgver.\n"
fi
```

I would like the output of this command, run every five seconds (or some other time period &mdash; if it were possible to set how long between execution of this script I'd be especially happy), to appear in the i3bar. I know how to do this for an i3bar controlled solely by a shell script (e.g., with the `status_command` line in `~/.i3/config`: `status_command ~/.i3/i3status.sh`), but I do not believe this is presently possible with i3pystatus managing the rest of the i3bar. If I am right in saying that this is not possible I would like to suggest that this capability be added to i3pystatus. 

Thanks for your time

**Comment by enkore** [comment]
https://i3pystatus.readthedocs.io/en/latest/i3pystatus.html#module-i3pystatus.shell

**Comment by fusion809** [comment]
Oops sorry, didn't see that in the docs. Thanks, closing.

**Comment by fusion809** [comment]
Ah doesn't seem compatible with the above shell snippet, I added it to /usr/local/bin/vimn and changed perms on /usr/local/bin/vimn to make it executable. Then I added this to my i3status.py script:

```python
status.register("shell",
    command="/bin/bash -c /usr/local/bin/vimn",
    interval="5")
```

and it gives this error:

![screenshot_20170707_235308](https://user-images.githubusercontent.com/4717341/27960663-77c7ed1c-636f-11e7-8aee-b309ddd57dca.png)

**Comment by fusion809** [comment]
Even adjusting the script so it is sh-compatible and changing command to "/usr/local/bin/vimn" doesn't fix this issue.

**Comment by enkore** [comment]
What's logged to ~/.i3pystatus.... ?

**Comment by enkore** [comment]
Try `interval=5` (without the "").

**Comment by fusion809** [comment]
I really need to learn to disregard quotation marks except when they are explicitly mentioned in the docs. Thanks, fixed it.
