### ISSUE TITLE
battery keyerror ENERGY_FULL

### ISSUE THREAD

**Issue by klloe** [enkore/i3pystatus#594]
Always worked so far, didn't change any of my config:

```
status.register('battery', 
                format='{consumption:.1f}W')

status.register('battery',
                format='{status} {percentage_design:.2f}%',
                status={
                    'DPL': 'DPL',
                    'CHR': 'CHR',
                    'DIS': 'BAT',
                    'FULL': 'FULL'
                })
```

The status bar shows:
```
BatteryChecker: KeyError: 'ENERGY_FULL'
```

![2017-07-10-124523_1366x768_scrot](https://user-images.githubusercontent.com/1057526/28014690-ed93cb06-656d-11e7-9f58-5dafaedd06f4.png)

**Comment by klloe** [comment]
It looks like, it doesn't work with i3status either.
![2017-07-10-125506_1366x768_scrot](https://user-images.githubusercontent.com/1057526/28015182-2229c4a0-656f-11e7-9b29-ec44e97a7c65.png)

**Comment by enkore** [comment]
Yes, some batteries or their drivers do not provide enough information to create a status display.
