### ISSUE TITLE
bit/s instead Bytes/s

### ISSUE THREAD

**Issue by 2Belette** [enkore/i3pystatus#599]
I know it is a simple and stupid question but I don't see how to display bit/s instead of bytes/s in `{bytes_sent}` and` {bytes_recv} `(network module)
I see a divisor option but I am more looking for a 8x multiplier option, I am sure I am missing something...

Thanks

**Comment by enkore** [comment]
1024/8 = 128 gives you kilobits.

**Comment by 2Belette** [comment]
outch ! you are right!
I guess there is no way to automatically "scale" the unit depending of the traffic ?
Would be nice instead of having the choice to have a big number if the interface is set to 1024/8 or sometimes noting if the interface is set to display mega only (1024*1024)/8

**Comment by TheMikeyR** [comment]
@2Belette I don't think so, the way I've dealt with it is by using this: `{bytes_recv:5d} \uf019{bytes_sent:10d} \uf093"` and a divisor of 1024, the 5d should create 5 empty chars where it can put a number. That way when I use my full bandwidth and download with e.g. 10 mb/s it fills out the all the empty spots in the line with 10000. I don't know why I need to double it up for bytes_sent, but if I keep that at 5d as well it doesn't render enough spaces. 
It looks like this:
![2017-10-09_13 43 12](https://user-images.githubusercontent.com/1436625/31336603-d001b41e-acf7-11e7-8e30-693a4feba08f.png)

My code for the two internet status
```
# Ethernet
status.register("network",
    interface="enp0s31f6",
    format_up="\uf062:{v4}:{bytes_recv:5d} \uf019{bytes_sent:10d} \uf093",
    graph_style="blocks",
    graph_width=5,
    #divisor=1048576) # Make byte/s to MB/s
    divisor=1024,
    recv_limit=10000,
    sent_limit=1000,
    end_color="yellow",
    separate_color=True,
    format_down="\uf062: DOWN")

# Wifi
status.register("network",
    interface="wlp4s0",
    format_down=": DOWN",
    format_up="{quality:03.0f}%{essid}:{v4}{bytes_recv:5d} \uf019 {bytes_sent:10d} \uf093",
    divisor=1024,
    recv_limit=10000,
    sent_limit=1000,)

```

**Comment by 2Belette** [comment]
@TheMikeyR thanks for the tips!
just for the reference I needed to comment `round_size` to make it work
