### ISSUE TITLE
Format output with padding

### ISSUE THREAD

**Issue by alefir** [enkore/i3pystatus#602]
Some modules output numbers that change in length frequently.
My example is the bytes_sent and bytes_recv from the Network module.
I would like to be able to pad the output of thise module with leading zeroes, so that the entire bar does not shift as my network usage changes.

**Comment by enkore** [comment]
e.g. `{bytes_recv:08d}`

**Comment by alefir** [comment]
thank you

**Comment by mcqueenjordan** [comment]
For me, `{bytes_recv:08d}` was raising `unknown format code d for object of type str`. I'm not sure if these became strings at some point or if there's a different reason.

In any case, I used the padding feature in the python formatting mini-language to achieve the same results:
e.g. `bytes_recv:0>3`

See https://docs.python.org/2/library/string.html#formatstrings

**Comment by RuiRojo** [comment]
@mcqueenjordan Does that still work for you? 

I'm not getting any padding with that (and using `08d` gives me the same error you got)

**Comment by enkore** [comment]
IIRC you can't have padding at the start / end of blocks, only inside.

**Comment by RuiRojo** [comment]
Oh. What so you mean by "blocks"? 

I've tested formats loe "DL: {network_graph_recv}{bytes_recv:0>8}/s | UL: stuff", where "{bytes_recv:0>8}" is inside the format string.

**Comment by enkore** [comment]
Block = what a module outputs. It should work for your use case. Do you use a serif font or a monospaced one? For a serif font a few spaces might be quite narrow.

**Comment by RuiRojo** [comment]
I'm not sure, it looks monospaced and sans serif. But ":0>8" is supposed to pad with 0's right? If so, I can't be missing them because they are too narrow. Even if they are spaces, they aren't taking any noticeable space.

I'm happy to know it should work, but I am not sure what to try to find out what's wrong.
