### ISSUE TITLE
[Error 24] Too many open files

### ISSUE THREAD

**Issue by CPrompt** [enkore/i3pystatus#603]
3 of the modules that I have running show errors after a bit of running.  It's not all the time, it just shows up after running for a few hours.  I cant mod+Shift+r to restart and the modules show correctly.

The modules are Network, Online and Disk

They will show [Error 24] Too many open files

I am running Fedora 26

Thanks!

**Comment by terminalmage** [comment]
Is this still happening? I would suggest creating a log file when initializing your `Status` object, like so:

```python
status = Status(logfile='/home/erik/var/i3pystatus.log')
```

This will allow you to get the full traceback if/when you see this again.

**Comment by CPrompt** [comment]
Haven't had an issue with it in quite some time.
