### ISSUE TITLE
calendar lacks documentation

### ISSUE THREAD

**Issue by teto** [enkore/i3pystatus#604]
I've tried to setup my calendar according to https://github.com/enkore/i3pystatus/pull/598
The doc https://i3pystatus.readthedocs.io/en/latest/ displays modules with several backend on the frontpage but it doesn't list the calendar backends there.

As for the Khal backend, config_path should not be mandatory (if set to None, khal falls back on the default one) and so does the "calendars" setting too IMO. I might send a patch for this when I get a tad more time.

**Comment by facetoe** [comment]
@teto I've updated the docs and fixed up the `Khal` backend.
