### ISSUE TITLE
xkblayout fatal error

### ISSUE THREAD

**Issue by danalec** [enkore/i3pystatus#606]
xkblayout: Fatal Error - AttributeError(/usr/lib/libX11.so.6: undefined symbol: cfree)

**Comment by savoisn** [comment]
Ran in the same issue ! :(

**Comment by hcpl** [comment]
@danalec @savoisn please update `xkbgroup` package to 0.2.0 where this is fixed.

**Comment by savoisn** [comment]
Awesome it's working for me !!

Thank you very much @hcpl
