### ISSUE TITLE
Full screen causes exited with status 0

### ISSUE THREAD

**Issue by MrBobBarker** [enkore/i3pystatus#609]
Whenever I go fullscreen with a window and return I found my status bar has crashed with this error in .xsession-errors:
[../../i3-wm-4.14/i3bar/src/child.c:462] ERROR: Child (pid: 26063) unexpectedly exited with status 0

I recently reinstalled from git which is when I began experiencing this issue.

**Comment by facetoe** [comment]
It's possible #601 is causing this. Do you get any exceptions in the i3pystatus log? Can you tell me which modules you have running? If you revert to the commit before #601 is the issue still present?

**Comment by MrBobBarker** [comment]
Building from 13a1caccd27b872da03c275d2c2bbbc112bca1e2 (1 before #601 ) fixes the issue. For the record this issue affected me regardless of what modules I loaded, including nothing and just a clock.

Thanks :+1:

**Comment by facetoe** [comment]
Hmm, can you try running the latest i3pystatus from the shell and sending it a `SIGUSR2` signal, eg:

    kill -SIGUSR2 $(pgrep -f <name of test script>)

Hopefully you will get a nice stacktrace.

**Comment by MrBobBarker** [comment]
Nothing happens, it just crashes as if I went into fullscreen. No console output, no additional logs in ~/.i3pystatus-* and nothing beyond the same error message in .xsession-errors.

**Comment by facetoe** [comment]
Well, that's unfortunate. It's strange that  it exits with return code `0`...

What is the output of:

    python --version

Does it also crash if you send `SIGUSR1`?

**Comment by MrBobBarker** [comment]
python --version
Python 2.7.14
python3 --version
Python 3.6.3rc1

Nothing different about using SIGUSR1.

**Comment by facetoe** [comment]
Hmm, well that is a good clue that it also exits on SIGUSR1. There must be something funny going on with the signal handling. I'll try to find some time tonight to try to reproduce this behaviour.

**Comment by facetoe** [comment]
OK, I figured out how to reproduce it. If you instantiate the `Status` class with `standalone=False`, the code that sets up the signal handlers is never executed. This means when `i3bar` sends the `SIGUSR2` signal on entering fullscreen mode it is not handled, and i3pystatus exits. Should be an easy fix.

**Comment by facetoe** [comment]
My bad, the above doesn't return 0.

**Comment by MrBobBarker** [comment]
My standalone is default (True), I tested it with false and my status bar shows blank. I also tried SIGUSR1 on my status script running in console and it doesn't exit, just immediately loops to new status interval.

**Comment by facetoe** [comment]
Can you try running this branch in the console  - https://github.com/facetoe/i3pystatus/tree/signal_test with the following config:

```python
from i3pystatus import Status

status = Status(standalone=True)
status.register("network")
status.run()
```
I want to try to understand where it's failing. When I run that branch I get the following output in `/tmp/test_log.log`:



On startup
```
i3pystatus.core.io 2017-09-22 21:42:34,303 DEBUG Setting refresh signal handler
i3pystatus.core.io 2017-09-22 21:42:34,304 DEBUG Setting suspend signal handler
```

After sending `SIGUSR2` once:
```
i3pystatus.core.io 2017-09-22 21:42:38,401 DEBUG suspend start: 12
i3pystatus.core.io 2017-09-22 21:42:38,401 DEBUG Stopped: True
i3pystatus.core.io 2017-09-22 21:42:38,402 DEBUG Suspending manager: 140294223164248
i3pystatus.core.threading 2017-09-22 21:42:38,402 DEBUG Suspending thread: Thread-2
i3pystatus.core.threading 2017-09-22 21:42:38,402 DEBUG Thread-2 suspended
i3pystatus.core.io 2017-09-22 21:42:38,403 DEBUG suspend end: 12
```

And a second time:
```
i3pystatus.core.io 2017-09-22 21:45:08,316 DEBUG suspend start: 12
i3pystatus.core.io 2017-09-22 21:45:08,316 DEBUG Stopped: False
i3pystatus.core.io 2017-09-22 21:45:08,316 DEBUG Resuming manager: 140294223164248
i3pystatus.core.threading 2017-09-22 21:45:08,317 DEBUG Resuming thread: Thread-2
i3pystatus.core.threading 2017-09-22 21:45:08,317 DEBUG Thread-2 resumed
i3pystatus.core.io 2017-09-22 21:45:08,317 DEBUG suspend end: 12

```

**Comment by lelit** [comment]
This happens to me too, after updating i3pystatus to current master.
It seems related to handling of the `keep_alive` feature: the parent Python process exits with 0 as soon as it receives the _stop_ event, so also my `dmenu -b` causes the problem.

**Comment by lelit** [comment]
Ah, I found the reason! My configuration contained the following:
```
bar {
        status_command python3 ~/.i3/status.py
        workspace_buttons yes
}
```
and thus there were **two** processes:
```
$ ps ax | grep status
28015 ?        S      0:00 /bin/sh -c python3 ~/.i3/status.py
28016 ?        Sl     0:00 python3 /home/lele/.i3/status.py
```
So it was the `bash` process the one receiving the `SIGSTOP` signal...

Now, using
```
bar {
        status_command exec python3 ~/.i3/status.py
        workspace_buttons yes
}
```

the problem is gone.

I'm still puzzled on why this was not happening before the upgrade...

**Comment by facetoe** [comment]
The `keep_alive` feature changed the signal sent by i3bar when it enters fullscreen mode or the bar is otherwise invisible. Previously it sent `SIGSTOP` on entering fullscreen mode and `SIGCONT` when exiting, now it sends `SIGUSR2` for both events and maintains a toggle within `i3pystatus`.

I hadn't considered that people might launch `i3pystatus` from another process such as `bash`,  which is a totally valid use case. I think it's best to put this feature behind a toggle and have it disabled by default.

**Comment by lelit** [comment]
Thanks. In my case, I think I can file the issue under _misconfiguration_ 😄

**Comment by facetoe** [comment]
Maybe, but it could be a pretty common configuration out in the wild. Most people won't use the `keep_alive` feature so best to not kill their status bar every time they enter full screen.

I mostly use it for the `abc_radio` module so the radio doesn't stop when the screen sleeps. I can't imagine that is a very popular module though.

@MrBobBarker, do you have a similar configuration in your `i3` config?

**Comment by lelit** [comment]
I agree. In my case I install a variant of the `notmuch` backend, that keeps track of whether there are new messages since the last update and in such case it emits a _red and urgent_ label: the behavior is exactly what I want, that is, I like it appear in red as soon as I'm back and bring back the control from the screen saver.

**Comment by MrBobBarker** [comment]
Yes, lelit's fix resolved my issue as well. Here's my log.

i3pystatus.core.io 2017-09-22 09:08:59,608 DEBUG Setting refresh signal handler
i3pystatus.core.io 2017-09-22 09:08:59,608 DEBUG Setting suspend signal handler
i3pystatus.core.io 2017-09-22 09:09:04,324 DEBUG suspend start: 12
i3pystatus.core.io 2017-09-22 09:09:04,325 DEBUG Stopped: True
i3pystatus.core.io 2017-09-22 09:09:04,325 DEBUG Suspending manager: 140439834568968
i3pystatus.core.threading 2017-09-22 09:09:04,325 DEBUG Suspending thread: Thread-2
i3pystatus.core.threading 2017-09-22 09:09:04,325 DEBUG Thread-2 suspended
i3pystatus.core.io 2017-09-22 09:09:04,325 DEBUG suspend end: 12
