### ISSUE TITLE
How to compile without overwriting i3pystatus

### ISSUE THREAD

**Issue by TheMikeyR** [enkore/i3pystatus#613]
Hello, I'm trying to build my own module (Like ABCRadio but for Danish radiostations), I've got so far that I would like to test my module, but hit a wall.
I currently have i3pystatus installed and I would like to "not fuck" that installation up, I've installed it from pip .
I would like to know how I can achieve on building i3pystatus from a fork by renaming it to something else so it doesn't destroy my current installation of i3pystatus. e.g. the way I can import my modified version is by `from i3pystatus_themikeyr import Status`

Thanks for your time and I'm sorry if this is a stupid question, still new to the "contribute" aspect.

**Comment by cyrilgdn** [comment]
@TheMikeyR 
`pip install --user -e /path/to/your/i3pystatus`

This will replace i3pystatus with yours and you can edit/test directly your module without having to reinstall anything.
When it's over, you can:
`pip uninstall i3pystatus`

It will remove your i3pystatus but let the original one (a second call to uninstall will remove the real package)

**Comment by terminalmage** [comment]
Another way of doing this would be to run i3pystatus in a virtualenv.

```
virtualenv /path/to/virtualenv
/path/to/virtualenv/bin/pip install --editable /path/to/your/git/checkout/of/i3pystatus
```

You can then run i3pystatus by using something like the following in your ``~/.config/i3/config``:

```
bar {
    status_command /path/to/virtualenv/bin/python /path/to/your/i3pystatus_config_script.py
}
```

This will allow you to make changes to your module, then restart i3 to reload i3pystatus and test your code updates.
