### ISSUE TITLE
Template: ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by fusion809** [enkore/i3pystatus#626]
Hi,

In the temperature field I am getting: `Temperature: ValueError: max() arg is an empty sequence`. This is what in my config file for i3pystatus loads the temperature module:

```python
status.register("temp",
    format="{Core_0}°C {Core_1}°C {Core_2}°C {Core_3}°C",
    hints={"markup": "pango"},
    lm_sensors_enabled=True,
    dynamic_color=True)
```

pango is installed as is the [colour module](https://github.com/vaab/colour) and [pysensors](https://github.com/bastienleonard/pysensors). The distro on which I'm testing this is a Gentoo (stable) system with the runit init system (doubt the init is relevant but nonetheless). The kernel version is 4.12.12-gentoo. If there is anything I can do to help to fix this error I'll do it. 

Thanks for your time,
Brenton

**Comment by facetoe** [comment]
Could you execute your config in the shell and post the stacktrace? Also might help to double check you have `sensors` installed (`which sensors`).

**Comment by facetoe** [comment]
Looks like this error is being thrown here - https://github.com/enkore/i3pystatus/blob/master/i3pystatus/temp.py#L209, so it looks like no sensors are found. Can you post the output of: `sensors`.

You should see something like the following:

```
⇒ sensors
acpitz-virtual-0
Adapter: Virtual device
temp1:        +53.0°C  (crit = +100.0°C)

coretemp-isa-0000
Adapter: ISA adapter
Core 0:       +53.0°C  (high = +84.0°C, crit = +100.0°C)
Core 1:       +52.0°C  (high = +84.0°C, crit = +100.0°C)
Core 2:       +53.0°C  (high = +84.0°C, crit = +100.0°C)
Core 3:       +52.0°C  (high = +84.0°C, crit = +100.0°C)
```

**Comment by fusion809** [comment]
The sensors command is installed, but it says it can't detect any sensors. But I suspect this problem may be related to the fact I'm running this system in a virtual machine. So I'll close unless you know a VM shouldn't make a difference. Thanks for your help.
