### ISSUE TITLE
On Gentoo Linux I get Temperature: KeyError: 'Core_0', but on Arch Linux all four core temperature fields are rendered perfectly

### ISSUE THREAD

**Issue by fusion809** [enkore/i3pystatus#629]
Hi,

On my Gentoo system I have installed [pysensors](https://github.com/bastienleonard/pysensors) with:

    pip3 install --user git+https://github.com/bastienleonard/pysensors.git

no errors were reported. lm_sensors is installed (which is actually required for this pip install to run properly, otherwise it fails complaining of missing lm_sensors headers). If relevant as to the USE flags here is `emerge -pqv sys-apps/lm_sensors`:

     [ebuild   R   ] sys-apps/lm_sensors-3.4.0_p20170901  USE="-contrib -sensord -static-libs" ABI_X86="(64) -32 (-x32)"

The lm_sensors daemon is running, if relevant, as I ran:

    /etc/init.d/lm_sensors

as root. 

I am using i3pystatus built from this repo's master branch, and I installed it with:

    pip3 install --user git+https://github.com/enkore/i3pystatus.git

no errors were reported. Every other part of my i3bar (managed with i3pystatus) is rendered perfectly:

![screenshot_20171203_092611](https://user-images.githubusercontent.com/4717341/33520714-0f6138ca-d80c-11e7-8c41-4ab99c4d7911.png)

Any ideas as to the problem? My i3 configs can be found [here](https://github.com/fusion809/i3-configs/tree/archlinux). On Arch Linux everything is rendered perfectly, including the cores.

Thanks for your time,
Brenton

**Comment by facetoe** [comment]
What is the output of `sensors`?

**Comment by fusion809** [comment]
```bash
acpitz-virtual-0
Adapter: Virtual device
temp1:        +85.0°C  (crit = +120.0°C)
temp2:        +76.0°C  (crit = +127.0°C)
temp3:        +49.0°C
```

**Comment by facetoe** [comment]
Doesn't look like you have a `Core 0` for whatever reason. Try changing the format string to: 

    {temp1} {temp2} {temp3}

**Comment by fusion809** [comment]
with:

     format="{temp1} {temp2} {temp3}",

I get: `Temperature: KeyError: 'temp3'`

**Comment by fusion809** [comment]
'tis odd, as you can probably guess leaving off the temp3 gets it to render perfectly, except with just two cores. On this PC under my Arch session all four cores are shown.

**Comment by fusion809** [comment]
Is it possible that the fact my Gentoo system uses the Btrfs file system instead of the one my Arch system uses, ext4, is relevant here?

**Comment by facetoe** [comment]
No I don't think the filesystem makes any difference. It's more likely that the version of lm_sensors differs and is returning different values. Are you able to check the output of `sensors` on both the Arch and Gentoo system and post the output?

I think the reason that `temp3` does not work is it doesn't appear to report a critical value and so it is skipped.

**Comment by fusion809** [comment]
On Arch it gives:

```
coretemp-isa-0000
Adapter: ISA adapter
Package id 0:  +63.0°C  (high = +84.0°C, crit = +100.0°C)
Core 0:        +63.0°C  (high = +84.0°C, crit = +100.0°C)
Core 1:        +58.0°C  (high = +84.0°C, crit = +100.0°C)
Core 2:        +61.0°C  (high = +84.0°C, crit = +100.0°C)
Core 3:        +57.0°C  (high = +84.0°C, crit = +100.0°C)

acpitz-virtual-0
Adapter: Virtual device
temp1:        +58.0°C  (crit = +120.0°C)
temp2:        +59.0°C  (crit = +127.0°C)
temp3:        +44.0°C
```

**Comment by facetoe** [comment]
Yep, that explains it. For one reason or another the Gentoo system is not reporting the `Adapter: ISA adapter` section. If you figure out what's going on there then your config should work fine on both systems.

**Comment by fusion809** [comment]
The lm_sensors article at the Gentoo Wiki helped me fix it. Needed to edit my kernel config, adding:

```config
CONFIG_SENSORS_CORETEMP=y
```

to it.

**Comment by facetoe** [comment]
Excellent, glad you got it working.
