### ISSUE TITLE
Feature request: Add support for Btrfs to disk module

### ISSUE THREAD

**Issue by fusion809** [enkore/i3pystatus#631]
Hi,

I'm using the Btrfs file system and the i3pystatus disk module misreports disk space usage which I'm guessing is probably due to it using `df -h mountpoint` to determine disk usage which is incompatible with Btrfs. If you'd like me to point you in the right direction for determine Btrfs disk usage here is where I use to determine it on my root partition:

```bash
sudo btrfs fi show | head -n 3 | grep "devid" | cut -d ' ' -f 9
```

Thanks for your time,
Brenton

**Comment by chestm007** [comment]
i3pystatus uses `os.statvfs` to get information on the filesystem to process and determine disk usage etc.

would you mind sending me the output of 

```
python -c "mnt = '/'; import os; print(os.statvfs(mnt))"; lsblk; df -h; sudo btrfs fi show | head -n 3 | grep "devid" | cut -d ' ' -f 9
```
you'll have to change `mnt='/'` to something appropriate for your setup (preferably the root mount point of your btrfs partition, and also verify your command in the previous message is correct.

Cheers

**Comment by fusion809** [comment]
Lol, this was so long ago that I've since ditched Btrfs out of frustration, partly because `btrfs fi show` does a lousy job at reporting disk usage, with it once reporting 30% disk usage, when 100% of the disk was used.
