### ISSUE TITLE
Spaces following Unicode characters rendered as 0020 glyphs and not a space

### ISSUE THREAD

**Issue by kinghrothgar** [enkore/i3pystatus#633]
Spaces following Unicode icons are not rendered as spaces but instead missing font glyphs:

![2018-01-24_10-07-55](https://user-images.githubusercontent.com/1952767/35339439-a1fd3f02-00ee-11e8-99d1-24ba85302fee.png)

I'm not sure what is causing this. I don't see this problem anywhere else (in the rest of i3, in my terminal, ex.)

**Comment by WhyNotHugo** [comment]
I'm having this problem recently too -- I've no idea what triggered it, but there was no change in my config near the time this started failing.

**Comment by enkore** [comment]
Do you use some kind of icon font?

**Comment by WhyNotHugo** [comment]
Yes, I've font awesome installed. I'm starting to think that i3pystatus is picking up that same font for the space (and the font doesn't define it).

However, other non-space characters right after the icon work fine.

**Comment by krypt-n** [comment]
This has nothing to do with i3pystatus (it doesn't know anything about fonts). You are probably using `ttf-font-awesome` and the recent upgrade to 5.0 is causing the problem. I have not investigated it further, but a workaround is to use `otf-font-awesome` instead.

**Comment by WhyNotHugo** [comment]
Indeed, replacing `ttf-font-awesome` with `otf-font-awesome` fixed it for me.

**Comment by kinghrothgar** [comment]
This fixed it for me. It is still strange to me that the only place I have this problem is in i3pystatus. I'm guessing that is just coincidence. Thanks for the help!

**Comment by aureooms** [comment]
This also happens with `i3status`. Same fix works.
