### ISSUE TITLE
The plugin "online" fails

### ISSUE THREAD

**Issue by lucasew** [enkore/i3pystatus#634]
My network is working perfectly but the plugin says not.
I think is the test address
The line: address = ("google-public-dns-a.google.com", 53)
On i3pystatus.core.util.internet
Running it on linux mint 18.3 i3wm

**Comment by richese** [comment]
One server cannot possibly fit all network configurations. You can try changing it to your ISP DNS server.

I am for example using OpenDNS server:
```python
server = ("208.67.222.222", 53) # opendns.com primary DNS server
status = Status(standalone=True, interval=1, internet_check=server)
```
