### ISSUE TITLE
cmus module: format_not_running doesn't display whew player reaches the end.

### ISSUE THREAD

**Issue by mafrazz** [enkore/i3pystatus#639]
When I deliberately pause/stop the player the value from `format_not_running` shows correctely, but if the player reaches the end of a playlist and stop by itself, it keep showing `format` in the bar.

`0:00/0:00  - ` instead of `no music`

```
status.register("cmus",
    format = "{status} {song_elapsed}/{song_length}  {artist} - {title}",
    format_not_running = "no music",
    on_leftclick = "previous_song",
    on_middleclick = "playpause",
    on_rightclick = "next_song",
    status = {
        "paused": "x",
        "playing": "o",
        "stopped": "~",
    }
)
```

Same happens with `moc`.

**Comment by mafrazz** [comment]
Thanks for the response.
Sure it helps somehow, but still not a satisfatory format since it can only hide text and not include.

A `format_stopped` would be the ideal.

**Comment by rscholer** [comment]
There is no need to introduce a new option. Just tweak your configuration like this:

``` Python
status.register("cmus",
    format = "{status} [{song_elapsed}/{song_length}  {artist} - {title}]",
    status = {"stopped": "no music"}
)
```

**Comment by mafrazz** [comment]
You are right, thank you.
