### ISSUE TITLE
Make network module change divisor automatically.

### ISSUE THREAD

**Issue by crocket** [enkore/i3pystatus#642]
I'd like to see network module switch among KB/s, MB/s, and GB/s automatically.

For example, rather than 28325KB/s, I'd like to see 28MB/s.

This can be achieved by

1. setting min_threshold and max_threshold so that there are multiple network modules that appear and disappear according to network rate
2. or, making a single network module switch among KB/s, MB/s, and GB/s automatically.

**Comment by chestm007** [comment]
fixed in #684
