### ISSUE TITLE
If there is no internet during weathercom's init, it never initializes parser afterwards.

### ISSUE THREAD

**Issue by crocket** [enkore/i3pystatus#647]
This is a problem because I usually log into an i3 session before DHCP client fetches an IP address.

If there is no internet connection when weathercom's init is called, I see the following error in the next interval of weather.

```
2018-04-23 22:24:37,027 [ERROR   ][i3pystatus.weather.weathercom.Weathercom 319] Uncaught error occurred while checking weather. Exception follows:
Traceback (most recent call last):
  File "/usr/lib64/python3.5/site-packages/i3pystatus/weather/weathercom.py", line 207, in check_weather
    self.parser.get_weather_data(self.forecast_url)
AttributeError: 'Weathercom' object has no attribute 'parser'
```

I think weathercom backend should wait for internet to become available and then initialize itself and update itself for the first time.

## Suggested Fix

1. Remove `@require(internet)` from Weathercom's init method because it doesn't need an internet connection.
2. Add an option called `failure-interval` because I want weather module to be updated often while the computer is still fetching an IP address from a DHCP server.

**Comment by terminalmage** [comment]
I am without a laptop right now, but I should be able to look at this next week.
