### ISSUE TITLE
Formatter.format in python 3.7 doesn't support non-positional format argument

### ISSUE THREAD

**Issue by przemkovv** [enkore/i3pystatus#661]
From python 3.7 format_string paremeter of formatter.format is positional-only ( https://docs.python.org/3/library/string.html#string.Formatter.format ) and the following line results in an error:

https://github.com/enkore/i3pystatus/blob/35537e95eb215408f1548990feda1bbc47a7e9cc/i3pystatus/cpu_usage.py#L88

**Comment by enkore** [comment]
Thanks, fixed by 0dad095

(I mean I see their reasoning for the change, but given that positional-only parameters were never something you could actually *do* in Python... well... I guess I thought the general direction was to do less of that sort)
