### ISSUE TITLE
Latest version: adding custom modules get prefixed

### ISSUE THREAD

**Issue by kootenpv** [enkore/i3pystatus#663]
I used to have my own custom module, which I could register and use like:

    status.register("whereami_predict")

where `whereami_predict` was the name of a module right next to my personal `i3pystatusbar.py`.

As of the latest version in git, I now get an error `No modules named 'i3pystatus.whereami_predict'` (you can see it is getting prefixed).

How can I now incorporate my custom modules?

**Comment by enkore** [comment]
You could do `status.register(whereami_predict)` (after importing it) or `status.register(whereami_predict.YourModuleClas())` (after importing it).

**Comment by kootenpv** [comment]
Thanks, that solved it!
