### ISSUE TITLE
error following commit 0dad095

### ISSUE THREAD

**Issue by meriops** [enkore/i3pystatus#664]
Hi, 
Following commit https://github.com/enkore/i3pystatus/commit/0dad095c079d689c829f7d71a3cb62ec90debedb, I get ` CpuUsage: TypeError: format() missing 1 required positional argument: 'format_string' ` . Is there something we should adjust in the configuration file to accomodate the change in the `CpuUsage` module? This is probably a dumb question but my python is too basic to figure that on my own... 
Thanks

**Comment by Arvedui** [comment]
Are you sure you are using a version that contains that commit?
Because that is exactly the error I would expect with python 3.7 without that commit.

**Comment by meriops** [comment]
haha! Apparently not... It looks like I just need to be patient, or to use @verri's patch... Apologies for the noise...

**Comment by Arvedui** [comment]
Sorry I guess I was unclear. 0dad095c079d689c829f7d71a3cb62ec90debedb already fixes the problem for python 3.7. Just update i3pystatus to the current git master and you should be fine.

**Comment by DavidAntliff** [comment]
This exact error has just started appearing for me immediately after an upgrade to Python 3.10.1 (I'm not sure what I had previously - maybe 3.10.0?). My i3pystatus config hasn't changed. I'm using version 3.35.
