### ISSUE TITLE
Possible to show only current i3 workspace?

### ISSUE THREAD

**Issue by EvilMegaDroid** [enkore/i3pystatus#668]
I have a small laptop screen and I want to make every inch of the statusbar count. Was thinking of showing the name of current focus container so I can know who I have focus (can do this with border but its annoying). Now the point of writting this issue is that I was wondering if there's a way to only show the current in use workspace so I can save some space on the bar.

**Comment by Arvedui** [comment]
The workspace indicator on the left is from i3bar itself not from the status command.
i3bar is configured in your i3 config, but I believe what you want is currently not possible with i3bar. You can find all available options in [i3s user guide](https://i3wm.org/docs/userguide.html#_configuring_i3bar).

**Comment by richese** [comment]
What you could do is to disable workspace buttons in i3bar config and show current workspace name directly in i3pystatus. The downsides to this would be that there is slight update delay and I do not know of any way to fix it in top left corner.

See below gist with example how you can implement this with python-i3ipc:
https://gist.github.com/richese/63f95309845b606693a2600af95d21bf

**Comment by EvilMegaDroid** [comment]
I never though of that, I know some python myself and will try that script out and see If i can get it to work how i want it. Thanks
