### ISSUE TITLE
version 3.35 on pipy does not match the source in github

### ISSUE THREAD

**Issue by srgvg** [enkore/i3pystatus#692]
looking at https://pypi.org/project/i3pystatus/3.35/#files
and downloading the source, when I look at e.g. shell.py, it doesn't have the `ignore_empty_stdout` config parameter:

```
 serge  minos  ~/tmp 
➡  grep stdout i3pystatus-3.35/i3pystatus/shell.py 
 serge  minos  ~/tmp  1 
➡  grep stdout  ~/src/util/i3pystatus/i3pystatus/shell.py 
    ignore_empty_stdout = False
        ("ignore_empty_stdout", "Let the block be empty"),
        if not full_text and not self.ignore_empty_stdout:
```

**Comment by chestm007** [comment]
Hi, i think this is somewhat explained in #584
tl;dr the pypi package will be out of date as the recomended way to install i3poystatus is via git.
