### ISSUE TITLE
Improvements on the pomodoro module look

### ISSUE THREAD

**Issue by eupiteco** [enkore/i3pystatus#713]
I've just started using the pomodoro module and missed some formatting and color options. 
* A `inactive_format` so one can use an icon instead of the "Start pomodoro" words.
* Color options for all the displays: inactive, running and break to match Xresources palette
I am not familiar with python language, more into js and web frontend stuff, so if anyone can submit a PR or help with finding the pomodoro method and building instructions I would be glad to submit it myself.

**Comment by chestm007** [comment]
If you wouldn't mind, please take a look at the referenced PR #714

**Comment by eupiteco** [comment]
That was quick! Exactly what I was thinking of, thanks a lot!

**Comment by chestm007** [comment]
Cool, I'll close this out as the PR is merged :)
