### ISSUE TITLE
Bug - Network module and pango

### ISSUE THREAD

**Issue by tigerjack** [enkore/i3pystatus#716]
If pango is enabled in the network module, [here](https://github.com/enkore/i3pystatus/blob/master/i3pystatus/network.py#L444) you assign something like that to bytes_sent/recv `'bytes_sent': '<span color="#00ff00">0</span>'`.

So, the format string lines [here](https://github.com/enkore/i3pystatus/blob/master/i3pystatus/network.py#L483) and [here](https://github.com/enkore/i3pystatus/blob/master/i3pystatus/network.py#L485) fail, given that those values are strings, not numbers.

**Comment by chestm007** [comment]
That looks like i caused it, I'll take a look

**Comment by chestm007** [comment]
@tigerjack I've merged my changes, please let me know if this is still an issue

**Comment by tigerjack** [comment]
@chestm007 sorry for the late response, it seems to be solved.
