### ISSUE TITLE
temp is a constant 20 degrees - but sensors returns data

### ISSUE THREAD

**Issue by brettswift** [enkore/i3pystatus#754]
i3pystatus version 3.35
PopOs 
On a Matebook x Pro. 
Python= v3.7.3

I can't install pysensors `pip3 install pysensors` (install throws an exception) so I have to operate with lm_sensors disabled. 

The regular sensors output is returning: 

```
iwlwifi-virtual-0
Adapter: Virtual device
temp1:        +44.0°C  

pch_skylake-virtual-0
Adapter: Virtual device
temp1:        +45.0°C  

coretemp-isa-0000
Adapter: ISA adapter
Package id 0:  +47.0°C  (high = +100.0°C, crit = +100.0°C)
Core 0:        +47.0°C  (high = +100.0°C, crit = +100.0°C)
Core 1:        +47.0°C  (high = +100.0°C, crit = +100.0°C)
Core 2:        +47.0°C  (high = +100.0°C, crit = +100.0°C)
Core 3:        +47.0°C  (high = +100.0°C, crit = +100.0°C)

```
Yet,  it still shows 20C. 

Thoughts?  Can I send a debug log?  
 
I looked at the code briefly but not sure where temp.py: self.file is set..  so not sure how to run the command that populates it. 

My current workaround that doesn't do alert temperatures, is: 
```
status.register("shell",
    command="sensors | grep Adapter -A 1 -m 1 | grep temp | awk -d+ '{print $2}'",
)
```

**Comment by chestm007** [comment]
Can you post a snippet of your temp config?

mine looks something like
```
status.register(
    "temp",,
    file="/sys/class/hwmon/hwmon0/temp1_input",
    interval=0.1,
    format='{temp:.1f} °C'
)
```

by default this module uses `/sys/class/thermal/thermal_zone0/temp` as the temp reading, so `cat` ing or such might reveal whether or not the module is actually doing something wrong

**Comment by brettswift** [comment]
That might be it.  I'm not configuring the file option.   I got my configs from someone elses example and must have missed that part on the docs. 

https://github.com/brettswift/linux-dotfiles/blob/master/.config/i3/i3pystatus.conf#L154

Maybe that's the missing piece.   I had thought the file was coming from the code library somewhere.
