### ISSUE TITLE
Network "auto_units" invalid option

### ISSUE THREAD

**Issue by pmourer** [enkore/i3pystatus#774]
```
$ pacman -Qi i3pystatus
Name            : i3pystatus
Version         : r1721.0d7156b-1
```

When attempting to set the "auto_units" option on the network module, this causes an error:
```
# .config/i3pystatus/config.py
 status.register("network",
         format_up="{essid} [{v4}] ↑{bytes_sent} ↓{bytes_recv} {freq:1.0f}Ghz {quality_bar}",
         auto_units=True,
         interface="wlp0s20f3",
         start_color=green,
         end_color=red,
         freq_divisor=1000000000
         )
```
The module reads in the i3bar:
`network: Fatal Error - ConfigKeyError("Module 'Network': invalid option 'auto_units'")`

Either the documentation for this option should be updated (is it deprecated?) or the functionality of the module needs to be corrected

**Comment by enkore** [comment]
Update your install, 0d7156b is from 2018 and predates this option.

**Comment by pmourer** [comment]
gotcha, thanks for following up. Didn't look to see that the package in AUR was way out of date.
