### ISSUE TITLE
Error: status_command process exited unexpectedly (exit 1) on fresh install with barebones config file

### ISSUE THREAD

**Issue by josephemorgan91** [enkore/i3pystatus#775]
Hey there,

Just checking out this project and I'm having some issues. On Arch linux with i3-gapps.

I installed via `pip3 install git+https://github.com/enkore/i3pystatus.git` and copied the config file in the docs just for testing. Initially it seemed to work, but the bar was full of errors mentioning modules that weren't installed. I `pip install`ed the mentioned modules (colour and netifaces), and suddenly I'm getting nothing but Error: status_command process exited unexpectedly (exit 1) in that status bar.

I've tried:
`pip uninstall i3pystatus`, `pip uninstall colour` and `pip uninstall netifaces` followed by a reinstall via the `pip3` command. No change in the issue. I also cleared everything out of the config file except for:
`from i3pystatus import Status`
`status = Status()`
`status.run()`
And I'm gettin the same error.

If I execute my config file in the command line, the error that I get says:
`Traceback (most recent call last):
  File ".i3/i3status.py", line 1, in <module>
    from i3pystatus import Status
  File "/home/joe/.dotfiles/i3/.i3/i3pystatus.py", line 1, in <module>
    from i3pystatus import Status
ImportError: cannot import name 'Status' from partially initialized module 'i3pystatus' (most likely due to a circular import) (/home/joe/.dotfiles/i3/.i3/i3pystatus.py)`

Please let me know if there is any more info I can provide that would be helpful.

**Comment by enkore** [comment]
You can't have a file named "i3pystatus.py" next to your config (/home/joe/.dotfiles/i3/.i3/i3pystatus.py) and the config cannot be named "i3pystatus.py".
