### ISSUE TITLE
Bitcoin module broken?

### ISSUE THREAD

**Issue by mxlian** [enkore/i3pystatus#798]
Bitcoinaverage.com seems to not allow free random requests anymore:

![image](https://user-images.githubusercontent.com/2795329/99529142-edd51300-29d1-11eb-9ce6-5665d4b1b867.png)

If i do the request manually i get this:
![image](https://user-images.githubusercontent.com/2795329/99529083-d85fe900-29d1-11eb-9e80-e4536fbc5998.png)

Can anyone else confirm this problem in the bticoin module?

**Comment by tyjak** [comment]
Yes, I desactivated this module since severals months now, the API used by this module isn't free anymore...

**Comment by tyjak** [comment]
@mxlian I made PR to fix the pb : https://github.com/enkore/i3pystatus/pull/801

**Comment by mxlian** [comment]
Great @tyjak , thanks so much
