### ISSUE TITLE
Lots of "invalid option" when running under python3.10

### ISSUE THREAD

**Issue by Kunsi** [enkore/i3pystatus#834]
I just updated my arch linux install to python 3.10, which leads to lots of modules having "invalid option" errors.

I'm running [this config file](https://git.franzi.business/kunsi/dotfiles/src/branch/main/.config/i3pystatus/config.py).

Errors:
- Module 'Network': invalid option 'detect_active'
- Module 'Shell': invalid option 'ignore_empty_stdout'
- Module 'Temperature': invalid option 'dynamic_color'
- Module 'PulseAudio': invalid option 'sink'

According to [the documentation](https://i3pystatus.readthedocs.io/en/latest/i3pystatus.html), none of these options are invalid.

**Comment by terminalmage** [comment]
Also running Arch, with Python 3.10.1, and I cannot reproduce this when running your config.py.

**Comment by terminalmage** [comment]
Double-check that you're running from the head of the `current` branch.

**Comment by Kunsi** [comment]
You're right. I uninstalled i3pystatus, reinstalled it, works again. Not sure what happened here.
