### ISSUE TITLE
I provide this library with my blender add-on and when I enable my add-on I get this error 

### ISSUE THREAD

**Issue by fast-blender-add-ons-dot-com** [enkore/i3pystatus#851]
c:\users\w\appdata\roaming\blender foundation\blender\3.6\scripts\addons\fast\lib\i3pystatus\core\modules.py:144: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if cb is not "run":

I was hoping you could fix that real quick so my end users aren't alarmed it's just a small thing

**Comment by terminalmage** [comment]
This was fixed in 5a8eaf4027c8a41cefb29a3ff12975d0296defe3 nearly 4 years ago.

i3pystatus no longer has numbered releases, it seems like you might have installed a very old release. See the [installation instructions](https://i3pystatus.readthedocs.io/en/latest/installation.html) for more info.

**Comment by fast-blender-add-ons-dot-com** [comment]
I installed it very recently with PIP maybe you could check your P I P
distribution

**Comment by terminalmage** [comment]
No. As I said, there are no longer new releases.

Please do as I suggested, and check the linked installation instructions.

**Comment by terminalmage** [comment]
@enkore I think the Project Description on PyPI needs to be updated to explain the discontinuation of numbered releases, and link to the installation instructions on readthedocs.

**Comment by fast-blender-add-ons-dot-com** [comment]
Good point. ... OK I'll go ahead and check that and you should think about
moving it or removing it from the PIP depository so people aren't confused
but thank you very much for helping me with that I really appreciate that
