### ISSUE TITLE
Empty color string floods ~/.xsession-errors

### ISSUE THREAD

**Issue by elig0n** [enkore/i3pystatus#863]
My `disk` module had a `color=""` line which caused a flooding of such messages to the `~/.xsession-errors` file (which reached tens of GiBs in some time)

```
[libi3] ERROR: Could not parse color:
```

My suggestion is for you to consider adding a check that will replace an empty passed color with the default one.

**Comment by terminalmage** [comment]
@elig0n can you test the changes in https://github.com/enkore/i3pystatus/pull/864?

**Comment by elig0n** [comment]
> @elig0n can you test the changes in #864?

Works for me

**Comment by terminalmage** [comment]
Thanks, merged that PR. Sorry for the delay.
