### ISSUE TITLE
Wrong battery status displayed

### ISSUE THREAD

**Issue by skety** [enkore/i3pystatus#89]
Hi,
I installed i3pystatus today, and noticed something wrong. The battery status appear as charging, but my battery is already fully charged.
Text appearing in i3bar:
CHR 100.00%

My battery configuration:
status.register("battery",
format="{status} {percentage:.2f}% {remaining:%E%hh:%Mm}",
alert=True,
alert_percentage=5,)

~ $ cat /sys/class/power_supply/BAT0/uevent
POWER_SUPPLY_NAME=BAT0
POWER_SUPPLY_STATUS=Full
POWER_SUPPLY_PRESENT=1
POWER_SUPPLY_TECHNOLOGY=Li-ion
POWER_SUPPLY_CYCLE_COUNT=0
POWER_SUPPLY_VOLTAGE_MIN_DESIGN=11100000
POWER_SUPPLY_VOLTAGE_NOW=12130000
POWER_SUPPLY_CURRENT_NOW=1000
POWER_SUPPLY_CHARGE_FULL_DESIGN=4400000
POWER_SUPPLY_CHARGE_FULL=3544000
POWER_SUPPLY_CHARGE_NOW=3544000
POWER_SUPPLY_CAPACITY=100
POWER_SUPPLY_MODEL_NAME=Dell
POWER_SUPPLY_MANUFACTURER=SANYO
POWER_SUPPLY_SERIAL_NUMBER=687

If I unplug the charger, the right "DIS" status appears.
Please let me know if I can be of further help.
Thanks

**Comment by s-hell** [comment]
Same Problem here:
$ cat /cats/class/power_supply/BAT0/uevent 
POWER_SUPPLY_NAME=BAT0
POWER_SUPPLY_STATUS=Discharging
POWER_SUPPLY_PRESENT=1
POWER_SUPPLY_TECHNOLOGY=Li-ion
POWER_SUPPLY_CYCLE_COUNT=0
POWER_SUPPLY_VOLTAGE_MIN_DESIGN=14800000
POWER_SUPPLY_VOLTAGE_NOW=14413000
POWER_SUPPLY_CHARGE_FULL_DESIGN=5200000
POWER_SUPPLY_CHARGE_FULL=4958000
POWER_SUPPLY_CHARGE_NOW=2653000
POWER_SUPPLY_CAPACITY=53
POWER_SUPPLY_CAPACITY_LEVEL=Normal
POWER_SUPPLY_MODEL_NAME=BAT
POWER_SUPPLY_MANUFACTURER=NOTEBOOK
POWER_SUPPLY_SERIAL_NUMBER=0001

 status.register("battery",
     battery_ident="BAT0",
     format="{status} {percentage_design:.1f}%",
     alert=True,
     alert_percentage=10,
     color="#008800",
     charging_color="#008800",
     full_color="#00ff00",
     status={
         "DPL": "X",
         "DIS": "↓",
         "CHR": "↑",
         "FULL": "=",
    },)

Running the current version.

**Comment by enkore** [comment]
What's the output of i3pystatus in this case?

**Comment by s-hell** [comment]
It says FULL

**Comment by enkore** [comment]
Ah, I guess it's because there is no information available about current / power drawn currently. But it should at least get the state right...

**Comment by s-hell** [comment]
It doesn't matter if i have one percent ore 90 percent. It always says FULL

**Comment by enkore** [comment]
This should fix it. Before there was some miscommunication between the layers by using "-1" as a "nope, don't have that" value.

**Comment by s-hell** [comment]
Looks good!
